window.WIIINFO_LANGUAGES = {
  ko: { label: "한국어", native: "한국어", flag: "🇰🇷", speech: "ko-KR" },
  th: { label: "태국어", native: "ไทย", flag: "🇹🇭", speech: "th-TH" },
  ja: { label: "일본어", native: "日本語", flag: "🇯🇵", speech: "ja-JP" },
  en: { label: "영어", native: "English", flag: "🇺🇸", speech: "en-US" },
  zh: { label: "중국어", native: "中文", flag: "🇨🇳", speech: "zh-CN" },
  vi: { label: "베트남어", native: "Tiếng Việt", flag: "🇻🇳", speech: "vi-VN" },
  es: { label: "스페인어", native: "Español", flag: "🇪🇸", speech: "es-ES" }
};

window.WIIINFO_LANGUAGE_NAMES = {
  ko: { ko: "한국어", th: "태국어", ja: "일본어", en: "영어", zh: "중국어", vi: "베트남어", es: "스페인어" },
  th: { ko: "ภาษาเกาหลี", th: "ภาษาไทย", ja: "ภาษาญี่ปุ่น", en: "ภาษาอังกฤษ", zh: "ภาษาจีน", vi: "ภาษาเวียดนาม", es: "ภาษาสเปน" },
  ja: { ko: "韓国語", th: "タイ語", ja: "日本語", en: "英語", zh: "中国語", vi: "ベトナム語", es: "スペイン語" },
  en: { ko: "Korean", th: "Thai", ja: "Japanese", en: "English", zh: "Chinese", vi: "Vietnamese", es: "Spanish" },
  zh: { ko: "韩语", th: "泰语", ja: "日语", en: "英语", zh: "中文", vi: "越南语", es: "西班牙语" },
  vi: { ko: "Tiếng Hàn", th: "Tiếng Thái", ja: "Tiếng Nhật", en: "Tiếng Anh", zh: "Tiếng Trung", vi: "Tiếng Việt", es: "Tiếng Tây Ban Nha" },
  es: { ko: "Coreano", th: "Tailandés", ja: "Japonés", en: "Inglés", zh: "Chino", vi: "Vietnamita", es: "Español" }
};

window.WIIINFO_LEARNER_PROFILES = [
  { id: "ko", label: "한국인이 배워요", native: "한국어 기준", flag: "🇰🇷", source: "ko", targets: ["th", "ja", "en", "zh", "vi", "es"] },
  { id: "th", label: "คนไทยเรียน", native: "태국어 기준", flag: "🇹🇭", source: "th", targets: ["ko", "ja", "en", "zh", "vi", "es"] },
  { id: "ja", label: "日本人が学ぶ", native: "일본어 기준", flag: "🇯🇵", source: "ja", targets: ["ko", "th", "en", "zh", "vi", "es"] },
  { id: "en", label: "English speaker", native: "영어 기준", flag: "🇺🇸", source: "en", targets: ["ko", "th", "ja", "zh", "vi", "es"] },
  { id: "zh", label: "中文使用者学习", native: "중국어 기준", flag: "🇨🇳", source: "zh", targets: ["ko", "th", "ja", "en", "vi", "es"] },
  { id: "vi", label: "Người Việt học", native: "베트남어 기준", flag: "🇻🇳", source: "vi", targets: ["ko", "th", "ja", "en", "zh", "es"] },
  { id: "es", label: "Hablante español", native: "스페인 기준", flag: "🇪🇸", source: "es", targets: ["ko", "th", "ja", "en", "zh", "vi"] }
];

window.WIIINFO_UI_COPY = {
  ko: {
    total: "학습 항목", favorites: "즐겨찾기", today: "오늘 학습", audience: "Choose your country",
    countryQuestion: "당신은 어느 나라 사람입니까?", target: "Learn", mode: "Mode", voice: "Voice",
    phrases: "문장", letters: "문자", female: "여성", male: "남성", quiz: "기준 언어 먼저 보기",
    searchPhrases: "문장, 뜻, 발음 검색", searchLetters: "문자, 이름, 발음 검색", hide: "가리기",
    infoEyebrow: "Korea info by Wii", phraseListLabel: "문장 목록", letterListLabel: "문자 목록",
    showMore: "{count}개 더보기", showingCount: "{visible}/{total}개 표시 중"
  },
  th: {
    total: "รายการเรียน", favorites: "บันทึก", today: "เรียนวันนี้", audience: "Choose your country",
    countryQuestion: "คุณมาจากประเทศอะไร?", target: "เรียน", mode: "โหมด", voice: "เสียง",
    phrases: "ประโยค", letters: "ตัวอักษร", female: "หญิง", male: "ชาย", quiz: "ดูภาษาของฉันก่อน",
    searchPhrases: "ค้นหาประโยค ความหมาย หรือเสียงอ่าน", searchLetters: "ค้นหาตัวอักษรหรือเสียง", hide: "ซ่อน",
    infoEyebrow: "ข้อมูลเกาหลี by Wii", phraseListLabel: "รายการประโยค", letterListLabel: "รายการตัวอักษร",
    showMore: "ดูเพิ่ม {count} รายการ", showingCount: "แสดง {visible}/{total} รายการ"
  },
  ja: {
    total: "学習項目", favorites: "お気に入り", today: "今日の学習", audience: "Choose your country",
    countryQuestion: "あなたはどこの国の人ですか？", target: "学ぶ", mode: "モード", voice: "音声",
    phrases: "文章", letters: "文字", female: "女性", male: "男性", quiz: "自分の言語を先に見る",
    searchPhrases: "文章・意味・発音を検索", searchLetters: "文字・名前・発音を検索", hide: "隠す",
    infoEyebrow: "Korea info by Wii", phraseListLabel: "文章リスト", letterListLabel: "文字リスト",
    showMore: "{count}件もっと見る", showingCount: "{visible}/{total}件を表示中"
  },
  en: {
    total: "Items", favorites: "Saved", today: "Today", audience: "Choose your country",
    countryQuestion: "Which country are you from?", target: "Learn", mode: "Mode", voice: "Voice",
    phrases: "Phrases", letters: "Letters", female: "Female", male: "Male", quiz: "Show my language first",
    searchPhrases: "Search phrase, meaning, or pronunciation", searchLetters: "Search letters or sounds", hide: "Hide",
    infoEyebrow: "Korea info by Wii", phraseListLabel: "Phrase list", letterListLabel: "Letter list",
    showMore: "Show {count} more", showingCount: "Showing {visible}/{total}"
  },
  zh: {
    total: "学习项目", favorites: "收藏", today: "今日学习", audience: "Choose your country",
    countryQuestion: "你来自哪个国家？", target: "学习", mode: "模式", voice: "声音",
    phrases: "句子", letters: "文字", female: "女声", male: "男声", quiz: "先看我的语言",
    searchPhrases: "搜索句子、意思或发音", searchLetters: "搜索文字或发音", hide: "隐藏",
    infoEyebrow: "韩国信息 by Wii", phraseListLabel: "句子列表", letterListLabel: "文字列表",
    showMore: "再看 {count} 个", showingCount: "正在显示 {visible}/{total}"
  },
  vi: {
    total: "Bài học", favorites: "Đã lưu", today: "Hôm nay", audience: "Choose your country",
    countryQuestion: "Bạn là người nước nào?", target: "Học", mode: "Chế độ", voice: "Giọng",
    phrases: "Câu", letters: "Chữ cái", female: "Nữ", male: "Nam", quiz: "Xem ngôn ngữ của tôi trước",
    searchPhrases: "Tìm câu, nghĩa hoặc phát âm", searchLetters: "Tìm chữ cái hoặc âm", hide: "Ẩn",
    infoEyebrow: "Thông tin Hàn Quốc by Wii", phraseListLabel: "Danh sách câu", letterListLabel: "Danh sách chữ cái",
    showMore: "Xem thêm {count}", showingCount: "Đang hiển thị {visible}/{total}"
  },
  es: {
    total: "Lecciones", favorites: "Guardado", today: "Hoy", audience: "Choose your country",
    countryQuestion: "¿De qué país eres?", target: "Aprender", mode: "Modo", voice: "Voz",
    phrases: "Frases", letters: "Letras", female: "Mujer", male: "Hombre", quiz: "Ver mi idioma primero",
    searchPhrases: "Buscar frase, significado o pronunciación", searchLetters: "Buscar letras o sonidos", hide: "Ocultar",
    infoEyebrow: "Información de Corea by Wii", phraseListLabel: "Lista de frases", letterListLabel: "Lista de letras",
    showMore: "Ver {count} más", showingCount: "Mostrando {visible}/{total}"
  }
};

window.WIIINFO_CATEGORY_LABELS = {
  ko: { "전체": "전체", "인사": "인사", "자기소개": "자기소개", "기초응답": "기초응답", "숫자/시간": "숫자/시간", "이동": "이동", "식당": "식당", "쇼핑": "쇼핑", "도움": "도움", "일상": "일상", "한국생활": "한국생활", "병원": "병원·약국", "은행": "은행·행정", "숙소": "숙소", "부동산": "부동산", "직장": "직장" },
  th: { "전체": "ทั้งหมด", "인사": "คำทักทาย", "자기소개": "แนะนำตัว", "기초응답": "คำตอบพื้นฐาน", "숫자/시간": "ตัวเลข/เวลา", "이동": "การเดินทาง", "식당": "ร้านอาหาร", "쇼핑": "ช้อปปิ้ง", "도움": "ขอความช่วยเหลือ", "일상": "ชีวิตประจำวัน", "한국생활": "ชีวิตในเกาหลี", "병원": "โรงพยาบาล·ร้านยา", "은행": "ธนาคาร·ราชการ", "숙소": "ที่พัก", "부동산": "อสังหาริมทรัพย์", "직장": "ที่ทำงาน" },
  ja: { "전체": "すべて", "인사": "あいさつ", "자기소개": "自己紹介", "기초응답": "基本応答", "숫자/시간": "数字/時間", "이동": "移動", "식당": "食堂", "쇼핑": "買い物", "도움": "助け", "일상": "日常", "한국생활": "韓国生活", "병원": "病院・薬局", "은행": "銀行・手続き", "숙소": "宿泊", "부동산": "不動産", "직장": "職場" },
  en: { "전체": "All", "인사": "Greetings", "자기소개": "Intro", "기초응답": "Basic replies", "숫자/시간": "Numbers/Time", "이동": "Transport", "식당": "Food", "쇼핑": "Shopping", "도움": "Help", "일상": "Daily life", "한국생활": "Life in Korea", "병원": "Hospital/Pharmacy", "은행": "Bank/Admin", "숙소": "Accommodation", "부동산": "Real estate", "직장": "Work" },
  zh: { "전체": "全部", "인사": "问候", "자기소개": "自我介绍", "기초응답": "基础回答", "숫자/시간": "数字/时间", "이동": "交通", "식당": "餐厅", "쇼핑": "购物", "도움": "帮助", "일상": "日常", "한국생활": "韩国生活", "병원": "医院·药店", "은행": "银行·手续", "숙소": "住宿", "부동산": "房地产", "직장": "职场" },
  vi: { "전체": "Tất cả", "인사": "Chào hỏi", "자기소개": "Giới thiệu", "기초응답": "Trả lời cơ bản", "숫자/시간": "Số/Giờ", "이동": "Di chuyển", "식당": "Ăn uống", "쇼핑": "Mua sắm", "도움": "Trợ giúp", "일상": "Hằng ngày", "한국생활": "Sống ở Hàn", "병원": "Bệnh viện·Nhà thuốc", "은행": "Ngân hàng·Thủ tục", "숙소": "Chỗ ở", "부동산": "Bất động sản", "직장": "Công việc" },
  es: { "전체": "Todo", "인사": "Saludos", "자기소개": "Presentación", "기초응답": "Respuestas básicas", "숫자/시간": "Números/Hora", "이동": "Transporte", "식당": "Comida", "쇼핑": "Compras", "도움": "Ayuda", "일상": "Vida diaria", "한국생활": "Vida en Corea", "병원": "Hospital/Farmacia", "은행": "Banco/Trámites", "숙소": "Alojamiento", "부동산": "Inmobiliaria", "직장": "Trabajo" }
};

// ⚠️ WIIINFO_INFO_SECTIONS(Korea info 가이드 생성기, 구 100~1769행)는 data/info-guide.js로 이동 (2026-06-04)
// app.js의 loadInfoGuide()가 지연 로드. 로드 전까지는 빈 객체.
window.WIIINFO_INFO_SECTIONS = window.WIIINFO_INFO_SECTIONS || {};

window.WIIINFO_EXTRA_PHRASES = [
  { en: "Hello.", ja: "こんにちは。", zh: "你好。", vi: "Xin chào.", es: "Hola.", ro: { en: "hello", ja: "konnichiwa", zh: "ni hao", vi: "sin chao", es: "ola" } },
  { en: "Hello. Nice to meet you.", ja: "こんにちは。お会いできてうれしいです。", zh: "你好。很高兴认识你。", vi: "Xin chào. Rất vui được gặp bạn.", es: "Hola. Encantado de conocerte.", ro: { en: "hello, nice to meet you", ja: "konnichiwa, o-ai dekite ureshii desu", zh: "ni hao, hen gao xing ren shi ni", vi: "sin chao, rat vui duoc gap ban", es: "ola, en-kan-ta-do de ko-no-ser-te" } },
  { en: "Thank you.", ja: "ありがとうございます。", zh: "谢谢。", vi: "Cảm ơn.", es: "Gracias.", ro: { en: "thank you", ja: "arigatou gozaimasu", zh: "xie xie", vi: "kam un", es: "gra-syas" } },
  { en: "Thank you very much.", ja: "本当にありがとうございます。", zh: "非常感谢。", vi: "Cảm ơn rất nhiều.", es: "Muchas gracias.", ro: { en: "thank you very much", ja: "hontou ni arigatou gozaimasu", zh: "fei chang gan xie", vi: "kam un rat nhieu", es: "mu-chas gra-syas" } },
  { en: "I'm sorry.", ja: "すみません。", zh: "对不起。", vi: "Xin lỗi.", es: "Lo siento.", ro: { en: "sorry", ja: "sumimasen", zh: "dui bu qi", vi: "sin loi", es: "lo syen-to" } },
  { en: "It's okay.", ja: "大丈夫です。", zh: "没关系。", vi: "Không sao.", es: "Está bien.", ro: { en: "it's okay", ja: "daijoubu desu", zh: "mei guan xi", vi: "khong sao", es: "es-ta byen" } },
  { en: "How are you?", ja: "お元気ですか。", zh: "你好吗？", vi: "Bạn khỏe không?", es: "¿Cómo estás?", ro: { en: "how are you", ja: "o-genki desu ka", zh: "ni hao ma", vi: "ban khoe khong", es: "ko-mo es-tas" } },
  { en: "I'm doing well.", ja: "元気です。", zh: "我很好。", vi: "Tôi khỏe.", es: "Estoy bien.", ro: { en: "I'm doing well", ja: "genki desu", zh: "wo hen hao", vi: "toi khoe", es: "es-toy byen" } },
  { en: "See you again.", ja: "また会いましょう。", zh: "下次见。", vi: "Hẹn gặp lại.", es: "Hasta luego.", ro: { en: "see you again", ja: "mata aimashou", zh: "xia ci jian", vi: "hen gap lai", es: "as-ta lwe-go" } },
  { en: "Goodbye.", ja: "さようなら。", zh: "再见。", vi: "Tạm biệt.", es: "Adiós.", ro: { en: "goodbye", ja: "sayounara", zh: "zai jian", vi: "tam biet", es: "a-dyos" } },
  { en: "I am Korean.", ja: "私は韓国人です。", zh: "我是韩国人。", vi: "Tôi là người Hàn Quốc.", es: "Soy coreano.", ro: { en: "I am Korean", ja: "watashi wa kankokujin desu", zh: "wo shi han guo ren", vi: "toi la nguoi han quoc", es: "soy ko-re-a-no" } },
  { en: "I am from Korea.", ja: "韓国から来ました。", zh: "我来自韩国。", vi: "Tôi đến từ Hàn Quốc.", es: "Soy de Corea.", ro: { en: "I am from Korea", ja: "kankoku kara kimashita", zh: "wo lai zi han guo", vi: "toi den tu han quoc", es: "soy de ko-re-a" } },
  { en: "My name is ___.", ja: "私の名前は___です。", zh: "我的名字是___。", vi: "Tên tôi là ___.", es: "Me llamo ___.", ro: { en: "my name is", ja: "watashi no namae wa ___ desu", zh: "wo de ming zi shi ___", vi: "ten toi la ___", es: "me ya-mo ___" } },
  { en: "What is your name?", ja: "お名前は何ですか。", zh: "你叫什么名字？", vi: "Bạn tên là gì?", es: "¿Cómo te llamas?", ro: { en: "what is your name", ja: "o-namae wa nan desu ka", zh: "ni jiao shen me ming zi", vi: "ban ten la gi", es: "ko-mo te ya-mas" } },
  { en: "I am learning Thai.", ja: "私はタイ語を勉強しています。", zh: "我正在学习泰语。", vi: "Tôi đang học tiếng Thái.", es: "Estoy aprendiendo tailandés.", ro: { en: "I am learning Thai", ja: "watashi wa taigo o benkyou shiteimasu", zh: "wo zai xue xi tai yu", vi: "toi dang hoc tieng thai", es: "es-toy a-pren-dyen-do tai-lan-des" } },
  { en: "I can speak a little Thai.", ja: "タイ語を少し話せます。", zh: "我会说一点泰语。", vi: "Tôi nói được một chút tiếng Thái.", es: "Hablo un poco de tailandés.", ro: { en: "I can speak a little Thai", ja: "taigo o sukoshi hanasemasu", zh: "wo hui shuo yi dian tai yu", vi: "toi noi duoc mot chut tieng thai", es: "a-blo un po-ko de tai-lan-des" } },
  { en: "I can speak a little English.", ja: "英語を少し話せます。", zh: "我会说一点英语。", vi: "Tôi nói được một chút tiếng Anh.", es: "Hablo un poco de inglés.", ro: { en: "I can speak a little English", ja: "eigo o sukoshi hanasemasu", zh: "wo hui shuo yi dian ying yu", vi: "toi noi duoc mot chut tieng anh", es: "a-blo un po-ko de in-gles" } },
  { en: "I understand.", ja: "分かりました。", zh: "我明白了。", vi: "Tôi hiểu rồi.", es: "Entiendo.", ro: { en: "I understand", ja: "wakarimashita", zh: "wo ming bai le", vi: "toi hieu roi", es: "en-tyen-do" } },
  { en: "I don't understand.", ja: "分かりません。", zh: "我不明白。", vi: "Tôi không hiểu.", es: "No entiendo.", ro: { en: "I don't understand", ja: "wakarimasen", zh: "wo bu ming bai", vi: "toi khong hieu", es: "no en-tyen-do" } },
  { en: "Please speak slowly.", ja: "ゆっくり話してください。", zh: "请慢一点说。", vi: "Vui lòng nói chậm thôi.", es: "Por favor, habla despacio.", ro: { en: "please speak slowly", ja: "yukkuri hanashite kudasai", zh: "qing man yi dian shuo", vi: "vui long noi cham thoi", es: "por fa-vor, a-bla des-pa-syo" } },
  { en: "Yes.", ja: "はい。", zh: "是的。", vi: "Vâng.", es: "Sí.", ro: { en: "yes", ja: "hai", zh: "shi de", vi: "vang", es: "si" } },
  { en: "No.", ja: "いいえ。", zh: "不是。", vi: "Không.", es: "No.", ro: { en: "no", ja: "iie", zh: "bu shi", vi: "khong", es: "no" } },
  { en: "That's right.", ja: "その通りです。", zh: "对的。", vi: "Đúng rồi.", es: "Correcto.", ro: { en: "that's right", ja: "sono toori desu", zh: "dui de", vi: "dung roi", es: "ko-rek-to" } },
  { en: "That's not right.", ja: "違います。", zh: "不对。", vi: "Không đúng.", es: "No es correcto.", ro: { en: "that's not right", ja: "chigaimasu", zh: "bu dui", vi: "khong dung", es: "no es ko-rek-to" } },
  { en: "Good.", ja: "いいです。", zh: "很好。", vi: "Tốt.", es: "Está bien.", ro: { en: "good", ja: "ii desu", zh: "hen hao", vi: "tot", es: "es-ta byen" } },
  { en: "Not good.", ja: "よくありません。", zh: "不好。", vi: "Không tốt.", es: "No está bien.", ro: { en: "not good", ja: "yoku arimasen", zh: "bu hao", vi: "khong tot", es: "no es-ta byen" } },
  { en: "Are you okay?", ja: "大丈夫ですか。", zh: "你还好吗？", vi: "Bạn ổn không?", es: "¿Estás bien?", ro: { en: "are you okay", ja: "daijoubu desu ka", zh: "ni hai hao ma", vi: "ban on khong", es: "es-tas byen" } },
  { en: "I'm okay.", ja: "大丈夫です。", zh: "我没事。", vi: "Tôi ổn.", es: "Estoy bien.", ro: { en: "I'm okay", ja: "daijoubu desu", zh: "wo mei shi", vi: "toi on", es: "es-toy byen" } },
  { en: "No problem.", ja: "問題ありません。", zh: "没问题。", vi: "Không có vấn đề gì.", es: "No hay problema.", ro: { en: "no problem", ja: "mondai arimasen", zh: "mei wen ti", vi: "khong co van de gi", es: "no ai pro-ble-ma" } },
  { en: "Please say it again.", ja: "もう一度言ってください。", zh: "请再说一遍。", vi: "Vui lòng nói lại.", es: "Por favor, dilo otra vez.", ro: { en: "please say it again", ja: "mou ichido itte kudasai", zh: "qing zai shuo yi bian", vi: "vui long noi lai", es: "por fa-vor di-lo o-tra ves" } },
  { en: "How much is this?", ja: "これはいくらですか。", zh: "这个多少钱？", vi: "Cái này bao nhiêu tiền?", es: "¿Cuánto cuesta esto?", ro: { en: "how much is this", ja: "kore wa ikura desu ka", zh: "zhe ge duo shao qian", vi: "cai nay bao nhieu tien", es: "kwan-to kwes-ta es-to" } },
  { en: "It's too expensive.", ja: "高すぎます。", zh: "太贵了。", vi: "Đắt quá.", es: "Es demasiado caro.", ro: { en: "it's too expensive", ja: "takasugimasu", zh: "tai gui le", vi: "dat qua", es: "es de-ma-sya-do ka-ro" } },
  { en: "Please give me a discount.", ja: "少し安くしてください。", zh: "请便宜一点。", vi: "Vui lòng giảm giá một chút.", es: "Por favor, hazme un descuento.", ro: { en: "please give me a discount", ja: "sukoshi yasuku shite kudasai", zh: "qing pian yi yi dian", vi: "vui long giam gia mot chut", es: "por fa-vor as-me un des-kwen-to" } },
  { en: "What time is it?", ja: "何時ですか。", zh: "现在几点？", vi: "Mấy giờ rồi?", es: "¿Qué hora es?", ro: { en: "what time is it", ja: "nanji desu ka", zh: "xian zai ji dian", vi: "may gio roi", es: "ke o-ra es" } },
  { en: "It's today.", ja: "今日です。", zh: "是今天。", vi: "Là hôm nay.", es: "Es hoy.", ro: { en: "it's today", ja: "kyou desu", zh: "shi jin tian", vi: "la hom nay", es: "es oy" } },
  { en: "It's tomorrow.", ja: "明日です。", zh: "是明天。", vi: "Là ngày mai.", es: "Es mañana.", ro: { en: "it's tomorrow", ja: "ashita desu", zh: "shi ming tian", vi: "la ngay mai", es: "es ma-nya-na" } },
  { en: "It was yesterday.", ja: "昨日です。", zh: "是昨天。", vi: "Là hôm qua.", es: "Fue ayer.", ro: { en: "it was yesterday", ja: "kinou desu", zh: "shi zuo tian", vi: "la hom qua", es: "fwe a-yer" } },
  { en: "I'll go now.", ja: "今行きます。", zh: "我现在去。", vi: "Tôi sẽ đi ngay bây giờ.", es: "Voy ahora.", ro: { en: "I'll go now", ja: "ima ikimasu", zh: "wo xian zai qu", vi: "toi se di ngay bay gio", es: "voy a-o-ra" } },
  { en: "Please wait a moment.", ja: "少々お待ちください。", zh: "请稍等。", vi: "Vui lòng đợi một chút.", es: "Espera un momento, por favor.", ro: { en: "please wait a moment", ja: "shoushou omachi kudasai", zh: "qing shao deng", vi: "vui long doi mot chut", es: "es-pe-ra un mo-men-to por fa-vor" } },
  { en: "It takes about ten minutes.", ja: "10分くらいかかります。", zh: "大约需要十分钟。", vi: "Mất khoảng mười phút.", es: "Tarda unos diez minutos.", ro: { en: "it takes about ten minutes", ja: "juppun kurai kakarimasu", zh: "da yue xu yao shi fen zhong", vi: "mat khoang muoi phut", es: "tar-da u-nos dyes mi-nu-tos" } },
  { en: "Where is this place?", ja: "ここはどこですか。", zh: "这里是哪里？", vi: "Đây là đâu?", es: "¿Dónde es este lugar?", ro: { en: "where is this place", ja: "koko wa doko desu ka", zh: "zhe li shi na li", vi: "day la dau", es: "don-de es es-te lu-gar" } },
  { en: "Where is the restroom?", ja: "トイレはどこですか。", zh: "洗手间在哪里？", vi: "Nhà vệ sinh ở đâu?", es: "¿Dónde está el baño?", ro: { en: "where is the restroom", ja: "toire wa doko desu ka", zh: "xi shou jian zai na li", vi: "nha ve sinh o dau", es: "don-de es-ta el ba-nyo" } },
  { en: "Where is the subway station?", ja: "地下鉄の駅はどこですか。", zh: "地铁站在哪里？", vi: "Ga tàu điện ngầm ở đâu?", es: "¿Dónde está la estación de metro?", ro: { en: "where is the subway station", ja: "chikatetsu no eki wa doko desu ka", zh: "di tie zhan zai na li", vi: "ga tau dien ngam o dau", es: "don-de es-ta la es-ta-syon de me-tro" } },
  { en: "Please come this way.", ja: "こちらへ来てください。", zh: "请往这边来。", vi: "Vui lòng đi lối này.", es: "Por favor, ven por aquí.", ro: { en: "please come this way", ja: "kochira e kite kudasai", zh: "qing wang zhe bian lai", vi: "vui long di loi nay", es: "por fa-vor ven por a-ki" } },
  { en: "Please go that way.", ja: "あちらへ行ってください。", zh: "请往那边走。", vi: "Vui lòng đi lối kia.", es: "Por favor, ve por allí.", ro: { en: "please go that way", ja: "achira e itte kudasai", zh: "qing wang na bian zou", vi: "vui long di loi kia", es: "por fa-vor ve por a-yi" } },
  { en: "Please go to the right.", ja: "右へ行ってください。", zh: "请往右走。", vi: "Vui lòng rẽ phải.", es: "Por favor, ve a la derecha.", ro: { en: "please go to the right", ja: "migi e itte kudasai", zh: "qing wang you zou", vi: "vui long re phai", es: "por fa-vor ve a la de-re-cha" } },
  { en: "Please go to the left.", ja: "左へ行ってください。", zh: "请往左走。", vi: "Vui lòng rẽ trái.", es: "Por favor, ve a la izquierda.", ro: { en: "please go to the left", ja: "hidari e itte kudasai", zh: "qing wang zuo zou", vi: "vui long re trai", es: "por fa-vor ve a la is-kier-da" } },
  { en: "Please go straight.", ja: "まっすぐ行ってください。", zh: "请一直走。", vi: "Vui lòng đi thẳng.", es: "Por favor, sigue recto.", ro: { en: "please go straight", ja: "massugu itte kudasai", zh: "qing yi zhi zou", vi: "vui long di thang", es: "por fa-vor si-ge rek-to" } },
  { en: "I want to take a taxi.", ja: "タクシーに乗りたいです。", zh: "我想坐出租车。", vi: "Tôi muốn đi taxi.", es: "Quiero tomar un taxi.", ro: { en: "I want to take a taxi", ja: "takushii ni noritai desu", zh: "wo xiang zuo chu zu che", vi: "toi muon di taxi", es: "kye-ro to-mar un tak-si" } },
  { en: "Please let me off here.", ja: "ここで降ろしてください。", zh: "请在这里停车。", vi: "Vui lòng cho tôi xuống ở đây.", es: "Déjame aquí, por favor.", ro: { en: "please let me off here", ja: "koko de oroshite kudasai", zh: "qing zai zhe li ting che", vi: "vui long cho toi xuong o day", es: "de-ha-me a-ki por fa-vor" } },
  { en: "Please give me the menu.", ja: "メニューをください。", zh: "请给我菜单。", vi: "Cho tôi xem thực đơn.", es: "Dame el menú, por favor.", ro: { en: "please give me the menu", ja: "menyuu o kudasai", zh: "qing gei wo cai dan", vi: "cho toi xem thuc don", es: "da-me el me-nu por fa-vor" } },
  { en: "Please give me this.", ja: "これをください。", zh: "请给我这个。", vi: "Cho tôi cái này.", es: "Dame esto, por favor.", ro: { en: "please give me this", ja: "kore o kudasai", zh: "qing gei wo zhe ge", vi: "cho toi cai nay", es: "da-me es-to por fa-vor" } },
  { en: "Please give me water.", ja: "水をください。", zh: "请给我水。", vi: "Cho tôi nước.", es: "Dame agua, por favor.", ro: { en: "please give me water", ja: "mizu o kudasai", zh: "qing gei wo shui", vi: "cho toi nuoc", es: "da-me a-gwa por fa-vor" } },
  { en: "Please make it not spicy.", ja: "辛くしないでください。", zh: "请不要辣。", vi: "Vui lòng đừng làm cay.", es: "Por favor, que no sea picante.", ro: { en: "please make it not spicy", ja: "karaku shinaide kudasai", zh: "qing bu yao la", vi: "vui long dung lam cay", es: "por fa-vor ke no se-a pi-kan-te" } },
  { en: "Please make it a little spicy.", ja: "少し辛くしてください。", zh: "请稍微辣一点。", vi: "Vui lòng làm hơi cay.", es: "Un poco picante, por favor.", ro: { en: "please make it a little spicy", ja: "sukoshi karaku shite kudasai", zh: "qing shao wei la yi dian", vi: "vui long lam hoi cay", es: "un po-ko pi-kan-te por fa-vor" } },
  { en: "It's delicious.", ja: "おいしいです。", zh: "很好吃。", vi: "Ngon lắm.", es: "Está delicioso.", ro: { en: "it's delicious", ja: "oishii desu", zh: "hen hao chi", vi: "ngon lam", es: "es-ta de-li-syo-so" } },
  { en: "Please bring the bill.", ja: "お会計をお願いします。", zh: "请结账。", vi: "Tính tiền giúp tôi.", es: "La cuenta, por favor.", ro: { en: "please bring the bill", ja: "okaikei o onegaishimasu", zh: "qing jie zhang", vi: "tinh tien giup toi", es: "la kwen-ta por fa-vor" } },
  { en: "Please pack it to go.", ja: "持ち帰りにしてください。", zh: "请打包。", vi: "Vui lòng gói mang về.", es: "Para llevar, por favor.", ro: { en: "please pack it to go", ja: "mochikaeri ni shite kudasai", zh: "qing da bao", vi: "vui long goi mang ve", es: "pa-ra ye-var por fa-vor" } },
  { en: "I have a food allergy.", ja: "食物アレルギーがあります。", zh: "我有食物过敏。", vi: "Tôi bị dị ứng thức ăn.", es: "Tengo alergia alimentaria.", ro: { en: "I have a food allergy", ja: "shokumotsu arerugii ga arimasu", zh: "wo you shi wu guo min", vi: "toi bi di ung thuc an", es: "ten-go a-ler-hya a-li-men-ta-rya" } },
  { en: "I don't eat meat.", ja: "肉は食べません。", zh: "我不吃肉。", vi: "Tôi không ăn thịt.", es: "No como carne.", ro: { en: "I don't eat meat", ja: "niku wa tabemasen", zh: "wo bu chi rou", vi: "toi khong an thit", es: "no ko-mo kar-ne" } },
  { en: "I want to buy this.", ja: "これを買いたいです。", zh: "我想买这个。", vi: "Tôi muốn mua cái này.", es: "Quiero comprar esto.", ro: { en: "I want to buy this", ja: "kore o kaitai desu", zh: "wo xiang mai zhe ge", vi: "toi muon mua cai nay", es: "kye-ro kom-prar es-to" } },
  { en: "Do you have another color?", ja: "他の色はありますか。", zh: "有别的颜色吗？", vi: "Có màu khác không?", es: "¿Tienes otro color?", ro: { en: "do you have another color", ja: "hoka no iro wa arimasu ka", zh: "you bie de yan se ma", vi: "co mau khac khong", es: "tye-nes o-tro ko-lor" } },
  { en: "Do you have another size?", ja: "他のサイズはありますか。", zh: "有别的尺码吗？", vi: "Có size khác không?", es: "¿Tienes otra talla?", ro: { en: "do you have another size", ja: "hoka no saizu wa arimasu ka", zh: "you bie de chi ma ma", vi: "co size khac khong", es: "tye-nes o-tra ta-ya" } },
  { en: "Can I try it on?", ja: "試着してもいいですか。", zh: "可以试穿吗？", vi: "Tôi thử được không?", es: "¿Puedo probármelo?", ro: { en: "can I try it on", ja: "shichaku shite mo ii desu ka", zh: "ke yi shi chuan ma", vi: "toi thu duoc khong", es: "pwe-do pro-bar-me-lo" } },
  { en: "Can I pay by card?", ja: "カードで払えますか。", zh: "可以刷卡吗？", vi: "Tôi thanh toán bằng thẻ được không?", es: "¿Puedo pagar con tarjeta?", ro: { en: "can I pay by card", ja: "kaado de haraemasu ka", zh: "ke yi shua ka ma", vi: "toi thanh toan bang the duoc khong", es: "pwe-do pa-gar kon tar-he-ta" } },
  { en: "I'll pay in cash.", ja: "現金で払います。", zh: "我用现金支付。", vi: "Tôi sẽ trả bằng tiền mặt.", es: "Pagaré en efectivo.", ro: { en: "I'll pay in cash", ja: "genkin de haraimasu", zh: "wo yong xian jin zhi fu", vi: "toi se tra bang tien mat", es: "pa-ga-re en e-fek-ti-vo" } },
  { en: "Please give me a receipt.", ja: "レシートをください。", zh: "请给我收据。", vi: "Cho tôi hóa đơn.", es: "Dame un recibo, por favor.", ro: { en: "please give me a receipt", ja: "reshiito o kudasai", zh: "qing gei wo shou ju", vi: "cho toi hoa don", es: "da-me un re-si-bo por fa-vor" } },
  { en: "Please give me a bag.", ja: "袋をください。", zh: "请给我袋子。", vi: "Cho tôi túi.", es: "Dame una bolsa, por favor.", ro: { en: "please give me a bag", ja: "fukuro o kudasai", zh: "qing gei wo dai zi", vi: "cho toi tui", es: "da-me u-na bol-sa por fa-vor" } },
  { en: "I'm just looking.", ja: "見ているだけです。", zh: "我只是看看。", vi: "Tôi chỉ xem thôi.", es: "Solo estoy mirando.", ro: { en: "I'm just looking", ja: "mite iru dake desu", zh: "wo zhi shi kan kan", vi: "toi chi xem thoi", es: "so-lo es-toy mi-ran-do" } },
  { en: "I like this.", ja: "これが気に入りました。", zh: "我喜欢这个。", vi: "Tôi thích cái này.", es: "Me gusta esto.", ro: { en: "I like this", ja: "kore ga kiniirimashita", zh: "wo xi huan zhe ge", vi: "toi thich cai nay", es: "me gus-ta es-to" } },
  { en: "Please help me.", ja: "助けてください。", zh: "请帮帮我。", vi: "Xin hãy giúp tôi.", es: "Ayúdame, por favor.", ro: { en: "please help me", ja: "tasukete kudasai", zh: "qing bang bang wo", vi: "xin hay giup toi", es: "a-yu-da-me por fa-vor" } },
  { en: "I'm lost.", ja: "道に迷いました。", zh: "我迷路了。", vi: "Tôi bị lạc đường.", es: "Estoy perdido.", ro: { en: "I'm lost", ja: "michi ni mayoimashita", zh: "wo mi lu le", vi: "toi bi lac duong", es: "es-toy per-di-do" } },
  { en: "I lost my phone.", ja: "携帯電話をなくしました。", zh: "我丢了手机。", vi: "Tôi bị mất điện thoại.", es: "Perdí mi teléfono.", ro: { en: "I lost my phone", ja: "keitai denwa o nakushimashita", zh: "wo diu le shou ji", vi: "toi bi mat dien thoai", es: "per-di mi te-le-fo-no" } },
  { en: "I lost my wallet.", ja: "財布をなくしました。", zh: "我丢了钱包。", vi: "Tôi bị mất ví.", es: "Perdí mi cartera.", ro: { en: "I lost my wallet", ja: "saifu o nakushimashita", zh: "wo diu le qian bao", vi: "toi bi mat vi", es: "per-di mi kar-te-ra" } },
  { en: "It hurts.", ja: "痛いです。", zh: "我疼。", vi: "Tôi bị đau.", es: "Me duele.", ro: { en: "it hurts", ja: "itai desu", zh: "wo teng", vi: "toi bi dau", es: "me dwe-le" } },
  { en: "I need to go to the hospital.", ja: "病院に行かなければなりません。", zh: "我需要去医院。", vi: "Tôi cần đến bệnh viện.", es: "Necesito ir al hospital.", ro: { en: "I need to go to the hospital", ja: "byouin ni ikanakereba narimasen", zh: "wo xu yao qu yi yuan", vi: "toi can den benh vien", es: "ne-se-si-to ir al os-pi-tal" } },
  { en: "Please call the police.", ja: "警察を呼んでください。", zh: "请叫警察。", vi: "Vui lòng gọi cảnh sát.", es: "Llama a la policía, por favor.", ro: { en: "please call the police", ja: "keisatsu o yonde kudasai", zh: "qing jiao jing cha", vi: "vui long goi canh sat", es: "ya-ma a la po-li-si-a por fa-vor" } },
  { en: "Can you speak Korean?", ja: "韓国語を話せますか。", zh: "你会说韩语吗？", vi: "Bạn nói được tiếng Hàn không?", es: "¿Puedes hablar coreano?", ro: { en: "can you speak Korean", ja: "kankokugo o hanasemasu ka", zh: "ni hui shuo han yu ma", vi: "ban noi duoc tieng han khong", es: "pwe-des a-blar ko-re-a-no" } },
  { en: "Can you speak English?", ja: "英語を話せますか。", zh: "你会说英语吗？", vi: "Bạn nói được tiếng Anh không?", es: "¿Puedes hablar inglés?", ro: { en: "can you speak English", ja: "eigo o hanasemasu ka", zh: "ni hui shuo ying yu ma", vi: "ban noi duoc tieng anh khong", es: "pwe-des a-blar in-gles" } },
  { en: "Can you take a photo for me?", ja: "写真を撮ってもらえますか。", zh: "可以帮我拍照吗？", vi: "Bạn chụp ảnh giúp tôi được không?", es: "¿Puedes tomarme una foto?", ro: { en: "can you take a photo for me", ja: "shashin o totte moraemasu ka", zh: "ke yi bang wo pai zhao ma", vi: "ban chup anh giup toi duoc khong", es: "pwe-des to-mar-me u-na fo-to" } },
  { en: "The weather is nice today.", ja: "今日は天気がいいです。", zh: "今天天气很好。", vi: "Hôm nay thời tiết đẹp.", es: "Hoy hace buen tiempo.", ro: { en: "the weather is nice today", ja: "kyou wa tenki ga ii desu", zh: "jin tian tian qi hen hao", vi: "hom nay thoi tiet dep", es: "oy a-se bwen tyem-po" } },
  { en: "It's cold today.", ja: "今日は寒いです。", zh: "今天很冷。", vi: "Hôm nay lạnh.", es: "Hoy hace frío.", ro: { en: "it's cold today", ja: "kyou wa samui desu", zh: "jin tian hen leng", vi: "hom nay lanh", es: "oy a-se fri-o" } },
  { en: "It's hot today.", ja: "今日は暑いです。", zh: "今天很热。", vi: "Hôm nay nóng.", es: "Hoy hace calor.", ro: { en: "it's hot today", ja: "kyou wa atsui desu", zh: "jin tian hen re", vi: "hom nay nong", es: "oy a-se ka-lor" } },
  { en: "It's raining.", ja: "雨が降っています。", zh: "下雨了。", vi: "Trời đang mưa.", es: "Está lloviendo.", ro: { en: "it's raining", ja: "ame ga futte imasu", zh: "xia yu le", vi: "troi dang mua", es: "es-ta yo-vyen-do" } },
  { en: "I'm tired.", ja: "疲れました。", zh: "我累了。", vi: "Tôi mệt.", es: "Estoy cansado.", ro: { en: "I'm tired", ja: "tsukaremashita", zh: "wo lei le", vi: "toi met", es: "es-toy kan-sa-do" } },
  { en: "I'm hungry.", ja: "お腹がすきました。", zh: "我饿了。", vi: "Tôi đói.", es: "Tengo hambre.", ro: { en: "I'm hungry", ja: "onaka ga sukimashita", zh: "wo e le", vi: "toi doi", es: "ten-go am-bre" } },
  { en: "I'm thirsty.", ja: "喉が渇きました。", zh: "我渴了。", vi: "Tôi khát.", es: "Tengo sed.", ro: { en: "I'm thirsty", ja: "nodo ga kawakimashita", zh: "wo ke le", vi: "toi khat", es: "ten-go sed" } },
  { en: "Are you okay?", ja: "大丈夫ですか。", zh: "你没事吧？", vi: "Bạn ổn chứ?", es: "¿Estás bien?", ro: { en: "are you okay", ja: "daijoubu desu ka", zh: "ni mei shi ba", vi: "ban on chu", es: "es-tas byen" } },
  { en: "Have a good day.", ja: "良い一日を。", zh: "祝你今天愉快。", vi: "Chúc bạn một ngày tốt lành.", es: "Que tengas un buen día.", ro: { en: "have a good day", ja: "yoi ichinichi o", zh: "zhu ni jin tian yu kuai", vi: "chuc ban mot ngay tot lanh", es: "ke ten-gas un bwen di-a" } },
  { en: "I'll contact you next time.", ja: "次回連絡します。", zh: "下次我会联系你。", vi: "Lần sau tôi sẽ liên lạc.", es: "Te contactaré la próxima vez.", ro: { en: "I'll contact you next time", ja: "jikai renraku shimasu", zh: "xia ci wo hui lian xi ni", vi: "lan sau toi se lien lac", es: "te kon-tak-ta-re la prok-si-ma ves" } },
  { en: "Please tell me the address.", ja: "住所を教えてください。", zh: "请告诉我地址。", vi: "Vui lòng cho tôi biết địa chỉ.", es: "Dime la dirección, por favor.", ro: { en: "please tell me the address", ja: "juusho o oshiete kudasai", zh: "qing gao su wo di zhi", vi: "vui long cho toi biet dia chi", es: "di-me la di-rek-syon por fa-vor" } },
  { en: "Please tell me the phone number.", ja: "電話番号を教えてください。", zh: "请告诉我电话号码。", vi: "Vui lòng cho tôi biết số điện thoại.", es: "Dime el número de teléfono, por favor.", ro: { en: "please tell me the phone number", ja: "denwa bangou o oshiete kudasai", zh: "qing gao su wo dian hua hao ma", vi: "vui long cho toi biet so dien thoai", es: "di-me el nu-me-ro de te-le-fo-no por fa-vor" } },
  { en: "Do you use KakaoTalk?", ja: "カカオトークを使いますか。", zh: "你用KakaoTalk吗？", vi: "Bạn có dùng KakaoTalk không?", es: "¿Usas KakaoTalk?", ro: { en: "do you use KakaoTalk", ja: "kakao tooku o tsukaimasu ka", zh: "ni yong KakaoTalk ma", vi: "ban co dung KakaoTalk khong", es: "u-sas KakaoTalk" } },
  { en: "I'll send you the map link.", ja: "地図リンクを送ります。", zh: "我会发送地图链接。", vi: "Tôi sẽ gửi link bản đồ.", es: "Te enviaré el enlace del mapa.", ro: { en: "I'll send you the map link", ja: "chizu rinku o okurimasu", zh: "wo hui fa song di tu lian jie", vi: "toi se gui link ban do", es: "te en-vya-re el en-la-se del ma-pa" } },
  { en: "An alien registration card is required.", ja: "外国人登録証が必要です。", zh: "需要外国人登录证。", vi: "Cần thẻ đăng ký người nước ngoài.", es: "Se necesita la tarjeta de registro de extranjero.", ro: { en: "alien registration card is required", ja: "gaikokujin tourokushou ga hitsuyou desu", zh: "xu yao wai guo ren deng lu zheng", vi: "can the dang ky nguoi nuoc ngoai", es: "se ne-se-si-ta la tar-he-ta de re-his-tro de eks-tran-he-ro" } },
  { en: "A passport is required.", ja: "パスポートが必要です。", zh: "需要护照。", vi: "Cần hộ chiếu.", es: "Se necesita el pasaporte.", ro: { en: "passport is required", ja: "pasupooto ga hitsuyou desu", zh: "xu yao hu zhao", vi: "can ho chieu", es: "se ne-se-si-ta el pa-sa-por-te" } },
  { en: "A reservation is required.", ja: "予約が必要です。", zh: "需要预约。", vi: "Cần đặt lịch trước.", es: "Se necesita una reserva.", ro: { en: "reservation is required", ja: "yoyaku ga hitsuyou desu", zh: "xu yao yu yue", vi: "can dat lich truoc", es: "se ne-se-si-ta u-na re-ser-va" } },
  { en: "Trash must be thrown away on the designated day.", ja: "ごみは決められた日に出します。", zh: "垃圾要在指定日期丢。", vi: "Rác phải bỏ đúng ngày quy định.", es: "La basura se tira en el día designado.", ro: { en: "trash must be thrown away on the designated day", ja: "gomi wa kimerareta hi ni dashimasu", zh: "la ji yao zai zhi ding ri qi diu", vi: "rac phai bo dung ngay quy dinh", es: "la ba-su-ra se ti-ra en el di-a de-sig-na-do" } },
  { en: "I need internet.", ja: "インターネットが必要です。", zh: "我需要网络。", vi: "Tôi cần internet.", es: "Necesito internet.", ro: { en: "I need internet", ja: "intaanetto ga hitsuyou desu", zh: "wo xu yao wang luo", vi: "toi can internet", es: "ne-se-si-to in-ter-net" } },
  { en: "I'll check it.", ja: "確認してみます。", zh: "我会确认一下。", vi: "Tôi sẽ kiểm tra.", es: "Lo revisaré.", ro: { en: "I'll check it", ja: "kakunin shite mimasu", zh: "wo hui que ren yi xia", vi: "toi se kiem tra", es: "lo re-vi-sa-re" } },

  // ===== 2026-06-04 확장분 (#101~200) =====
  { en: "Where is the bus stop?", ja: "バス停はどこですか。", zh: "公交车站在哪里？", vi: "Trạm xe buýt ở đâu?", es: "¿Dónde está la parada de autobús?", ro: { en: "where is the bus stop", ja: "basutei wa doko desu ka", zh: "gong jiao che zhan zai na li", vi: "tram xe buyt o dau", es: "don-de es-ta la pa-ra-da de au-to-bus" } },
  { en: "Does this bus go to Myeongdong?", ja: "このバスは明洞に行きますか。", zh: "这辆公交车去明洞吗？", vi: "Xe buýt này có đi Myeongdong không?", es: "¿Este autobús va a Myeongdong?", ro: { en: "does this bus go to Myeongdong", ja: "kono basu wa myondon ni ikimasu ka", zh: "zhe liang gong jiao che qu ming dong ma", vi: "xe buyt nay co di Myeongdong khong", es: "es-te au-to-bus va a Myeongdong" } },
  { en: "Where can I buy a ticket?", ja: "切符はどこで買えますか。", zh: "在哪里买票？", vi: "Mua vé ở đâu?", es: "¿Dónde puedo comprar un billete?", ro: { en: "where can I buy a ticket", ja: "kippu wa doko de kaemasu ka", zh: "zai na li mai piao", vi: "mua ve o dau", es: "don-de pwe-do kom-prar un bi-ye-te" } },
  { en: "How long does it take?", ja: "どのくらいかかりますか。", zh: "需要多长时间？", vi: "Mất bao lâu?", es: "¿Cuánto tiempo se tarda?", ro: { en: "how long does it take", ja: "dono kurai kakarimasu ka", zh: "xu yao duo chang shi jian", vi: "mat bao lau", es: "kwan-to tyem-po se tar-da" } },
  { en: "I'll get off here.", ja: "ここで降ります。", zh: "我在这里下车。", vi: "Tôi xuống ở đây.", es: "Me bajo aquí.", ro: { en: "I'll get off here", ja: "koko de orimasu", zh: "wo zai zhe li xia che", vi: "toi xuong o day", es: "me ba-ho a-ki" } },
  { en: "What is the next station?", ja: "次の駅はどこですか。", zh: "下一站是哪里？", vi: "Ga tiếp theo là ga nào?", es: "¿Cuál es la próxima estación?", ro: { en: "what is the next station", ja: "tsugi no eki wa doko desu ka", zh: "xia yi zhan shi na li", vi: "ga tiep theo la ga nao", es: "kwal es la prok-si-ma es-ta-syon" } },
  { en: "Could you look at this map with me?", ja: "地図を見てもらえますか。", zh: "可以帮我看一下地图吗？", vi: "Bạn xem giúp tôi bản đồ được không?", es: "¿Puedes mirar este mapa conmigo?", ro: { en: "could you look at this map", ja: "chizu o mite moraemasu ka", zh: "ke yi bang wo kan yi xia di tu ma", vi: "ban xem giup toi ban do duoc khong", es: "pwe-des mi-rar es-te ma-pa kon-mi-go" } },
  { en: "To the airport, please.", ja: "空港までお願いします。", zh: "请去机场。", vi: "Cho tôi đến sân bay.", es: "Al aeropuerto, por favor.", ro: { en: "to the airport please", ja: "kuukou made onegaishimasu", zh: "qing qu ji chang", vi: "cho toi den san bay", es: "al a-e-ro-pwer-to por fa-vor" } },
  { en: "I want to book a train ticket.", ja: "電車の切符を予約したいです。", zh: "我想订火车票。", vi: "Tôi muốn đặt vé tàu.", es: "Quiero reservar un billete de tren.", ro: { en: "I want to book a train ticket", ja: "densha no kippu o yoyaku shitai desu", zh: "wo xiang ding huo che piao", vi: "toi muon dat ve tau", es: "kye-ro re-ser-var un bi-ye-te de tren" } },
  { en: "Do I need to transfer?", ja: "乗り換えが必要ですか。", zh: "需要换乘吗？", vi: "Tôi có cần đổi tuyến không?", es: "¿Tengo que hacer transbordo?", ro: { en: "do I need to transfer", ja: "norikae ga hitsuyou desu ka", zh: "xu yao huan cheng ma", vi: "toi co can doi tuyen khong", es: "ten-go ke a-ser trans-bor-do" } },

  { en: "Do you have a table for two?", ja: "二人席はありますか。", zh: "有两个人的位子吗？", vi: "Có bàn cho hai người không?", es: "¿Tienen mesa para dos?", ro: { en: "do you have a table for two", ja: "futari seki wa arimasu ka", zh: "you liang ge ren de wei zi ma", vi: "co ban cho hai nguoi khong", es: "tye-nen me-sa pa-ra dos" } },
  { en: "I have a reservation.", ja: "予約してあります。", zh: "我有预约。", vi: "Tôi đã đặt chỗ rồi.", es: "Tengo una reserva.", ro: { en: "I have a reservation", ja: "yoyaku shite arimasu", zh: "wo you yu yue", vi: "toi da dat cho roi", es: "ten-go u-na re-ser-va" } },
  { en: "What do you recommend?", ja: "おすすめは何ですか。", zh: "推荐什么菜？", vi: "Món nào được gợi ý?", es: "¿Qué recomienda?", ro: { en: "what do you recommend", ja: "osusume wa nan desu ka", zh: "tui jian shen me cai", vi: "mon nao duoc goi y", es: "ke re-ko-myen-da" } },
  { en: "What kind of dish is this?", ja: "これはどんな料理ですか。", zh: "这是什么菜？", vi: "Đây là món gì?", es: "¿Qué plato es este?", ro: { en: "what kind of dish is this", ja: "kore wa donna ryouri desu ka", zh: "zhe shi shen me cai", vi: "day la mon gi", es: "ke pla-to es es-te" } },
  { en: "Less spicy, please.", ja: "辛さ控えめでお願いします。", zh: "请做得不那么辣。", vi: "Cho ít cay thôi.", es: "Menos picante, por favor.", ro: { en: "less spicy please", ja: "karasa hikaeme de onegaishimasu", zh: "qing zuo de bu na me la", vi: "cho it cay thoi", es: "me-nos pi-kan-te por fa-vor" } },
  { en: "No cilantro, please.", ja: "パクチー抜きでお願いします。", zh: "请不要放香菜。", vi: "Đừng cho rau mùi.", es: "Sin cilantro, por favor.", ro: { en: "no cilantro please", ja: "pakuchii nuki de onegaishimasu", zh: "qing bu yao fang xiang cai", vi: "dung cho rau mui", es: "sin si-lan-tro por fa-vor" } },
  { en: "Can I get a refill?", ja: "おかわりできますか。", zh: "可以续杯吗？", vi: "Có thể lấy thêm không?", es: "¿Puedo repetir?", ro: { en: "can I get a refill", ja: "okawari dekimasu ka", zh: "ke yi xu bei ma", vi: "co the lay them khong", es: "pwe-do re-pe-tir" } },
  { en: "Separate bills, please.", ja: "別々に会計してください。", zh: "请分开结账。", vi: "Tính tiền riêng giúp tôi.", es: "Cuentas separadas, por favor.", ro: { en: "separate bills please", ja: "betsubetsu ni kaikei shite kudasai", zh: "qing fen kai jie zhang", vi: "tinh tien rieng giup toi", es: "kwen-tas se-pa-ra-das por fa-vor" } },
  { en: "Can I take this to go?", ja: "持ち帰りできますか。", zh: "可以打包带走吗？", vi: "Có thể gói mang về không?", es: "¿Me lo puedo llevar?", ro: { en: "can I take this to go", ja: "mochikaeri dekimasu ka", zh: "ke yi da bao dai zou ma", vi: "co the goi mang ve khong", es: "me lo pwe-do ye-var" } },
  { en: "It was delicious. Thank you.", ja: "とてもおいしかったです。ありがとうございます。", zh: "非常好吃，谢谢。", vi: "Rất ngon. Cảm ơn.", es: "Estaba delicioso. Gracias.", ro: { en: "it was delicious, thank you", ja: "totemo oishikatta desu, arigatou gozaimasu", zh: "fei chang hao chi, xie xie", vi: "rat ngon, kam un", es: "es-ta-ba de-li-syo-so, gra-syas" } },

  { en: "Do you have anything cheaper?", ja: "もっと安いものはありますか。", zh: "有更便宜的吗？", vi: "Có cái nào rẻ hơn không?", es: "¿Tiene algo más barato?", ro: { en: "do you have anything cheaper", ja: "motto yasui mono wa arimasu ka", zh: "you geng pian yi de ma", vi: "co cai nao re hon khong", es: "tye-ne al-go mas ba-ra-to" } },
  { en: "A new one, please.", ja: "新しいものをください。", zh: "请给我一个新的。", vi: "Cho tôi cái mới.", es: "Uno nuevo, por favor.", ro: { en: "a new one please", ja: "atarashii mono o kudasai", zh: "qing gei wo yi ge xin de", vi: "cho toi cai moi", es: "u-no nwe-vo por fa-vor" } },
  { en: "Can I exchange this?", ja: "交換できますか。", zh: "可以换货吗？", vi: "Tôi đổi cái này được không?", es: "¿Puedo cambiarlo?", ro: { en: "can I exchange this", ja: "koukan dekimasu ka", zh: "ke yi huan huo ma", vi: "toi doi cai nay duoc khong", es: "pwe-do kam-byar-lo" } },
  { en: "I'd like a refund.", ja: "返金してください。", zh: "请给我退款。", vi: "Cho tôi hoàn tiền.", es: "Quiero un reembolso.", ro: { en: "I'd like a refund", ja: "henkin shite kudasai", zh: "qing gei wo tui kuan", vi: "cho toi hoan tien", es: "kye-ro un re-em-bol-so" } },
  { en: "Please gift-wrap it.", ja: "プレゼント用に包んでください。", zh: "请帮我包装成礼物。", vi: "Gói quà giúp tôi.", es: "Envuélvalo para regalo, por favor.", ro: { en: "please gift-wrap it", ja: "purezento you ni tsutsunde kudasai", zh: "qing bang wo bao zhuang cheng li wu", vi: "goi qua giup toi", es: "en-vwel-va-lo pa-ra re-ga-lo" } },
  { en: "Is it tax-free?", ja: "免税できますか。", zh: "可以免税吗？", vi: "Có hoàn thuế không?", es: "¿Es libre de impuestos?", ro: { en: "is it tax-free", ja: "menzei dekimasu ka", zh: "ke yi mian shui ma", vi: "co hoan thue khong", es: "es li-bre de im-pwes-tos" } },
  { en: "What are your opening hours?", ja: "営業時間は何時から何時までですか。", zh: "营业时间是几点到几点？", vi: "Giờ mở cửa từ mấy giờ đến mấy giờ?", es: "¿Cuál es el horario de apertura?", ro: { en: "what are your opening hours", ja: "eigyou jikan wa nanji kara nanji made desu ka", zh: "ying ye shi jian shi ji dian dao ji dian", vi: "gio mo cua tu may gio den may gio", es: "kwal es el o-ra-ryo de a-per-tu-ra" } },
  { en: "Two of these, please.", ja: "これを二つください。", zh: "请给我两个这个。", vi: "Cho tôi hai cái này.", es: "Dos de estos, por favor.", ro: { en: "two of these please", ja: "kore o futatsu kudasai", zh: "qing gei wo liang ge zhe ge", vi: "cho toi hai cai nay", es: "dos de es-tos por fa-vor" } },
  { en: "Do you have a bigger one?", ja: "もっと大きいものはありますか。", zh: "有更大的吗？", vi: "Có cái nào to hơn không?", es: "¿Tiene uno más grande?", ro: { en: "do you have a bigger one", ja: "motto ookii mono wa arimasu ka", zh: "you geng da de ma", vi: "co cai nao to hon khong", es: "tye-ne u-no mas gran-de" } },
  { en: "Which one is popular?", ja: "人気があるのはどれですか。", zh: "哪个最受欢迎？", vi: "Cái nào bán chạy?", es: "¿Cuál es el más popular?", ro: { en: "which one is popular", ja: "ninki ga aru no wa dore desu ka", zh: "na ge zui shou huan ying", vi: "cai nao ban chay", es: "kwal es el mas po-pu-lar" } },

  { en: "Where is the hospital?", ja: "病院はどこですか。", zh: "医院在哪里？", vi: "Bệnh viện ở đâu?", es: "¿Dónde está el hospital?", ro: { en: "where is the hospital", ja: "byouin wa doko desu ka", zh: "yi yuan zai na li", vi: "benh vien o dau", es: "don-de es-ta el os-pi-tal" } },
  { en: "Where is the pharmacy?", ja: "薬局はどこですか。", zh: "药店在哪里？", vi: "Nhà thuốc ở đâu?", es: "¿Dónde está la farmacia?", ro: { en: "where is the pharmacy", ja: "yakkyoku wa doko desu ka", zh: "yao dian zai na li", vi: "nha thuoc o dau", es: "don-de es-ta la far-ma-sya" } },
  { en: "I have a headache.", ja: "頭が痛いです。", zh: "我头疼。", vi: "Tôi bị đau đầu.", es: "Me duele la cabeza.", ro: { en: "I have a headache", ja: "atama ga itai desu", zh: "wo tou teng", vi: "toi bi dau dau", es: "me dwe-le la ka-be-sa" } },
  { en: "I have a stomachache.", ja: "お腹が痛いです。", zh: "我肚子疼。", vi: "Tôi bị đau bụng.", es: "Me duele el estómago.", ro: { en: "I have a stomachache", ja: "onaka ga itai desu", zh: "wo du zi teng", vi: "toi bi dau bung", es: "me dwe-le el es-to-ma-go" } },
  { en: "I have a fever.", ja: "熱があります。", zh: "我发烧了。", vi: "Tôi bị sốt.", es: "Tengo fiebre.", ro: { en: "I have a fever", ja: "netsu ga arimasu", zh: "wo fa shao le", vi: "toi bi sot", es: "ten-go fye-bre" } },
  { en: "I caught a cold.", ja: "風邪をひきました。", zh: "我感冒了。", vi: "Tôi bị cảm.", es: "Me resfrié.", ro: { en: "I caught a cold", ja: "kaze o hikimashita", zh: "wo gan mao le", vi: "toi bi cam", es: "me res-frye" } },
  { en: "I'm allergic to some medicine.", ja: "薬のアレルギーがあります。", zh: "我对某些药过敏。", vi: "Tôi bị dị ứng thuốc.", es: "Soy alérgico a algunos medicamentos.", ro: { en: "I'm allergic to some medicine", ja: "kusuri no arerugii ga arimasu", zh: "wo dui mou xie yao guo min", vi: "toi bi di ung thuoc", es: "soy a-ler-hi-ko a me-di-ka-men-tos" } },
  { en: "Do you have painkillers?", ja: "痛み止めはありますか。", zh: "有止痛药吗？", vi: "Có thuốc giảm đau không?", es: "¿Tiene analgésicos?", ro: { en: "do you have painkillers", ja: "itamidome wa arimasu ka", zh: "you zhi tong yao ma", vi: "co thuoc giam dau khong", es: "tye-ne a-nal-he-si-kos" } },
  { en: "How many times a day do I take it?", ja: "一日に何回飲みますか。", zh: "一天吃几次？", vi: "Một ngày uống mấy lần?", es: "¿Cuántas veces al día lo tomo?", ro: { en: "how many times a day do I take it", ja: "ichinichi ni nankai nomimasu ka", zh: "yi tian chi ji ci", vi: "mot ngay uong may lan", es: "kwan-tas ve-ses al di-a lo to-mo" } },
  { en: "I have insurance.", ja: "保険があります。", zh: "我有保险。", vi: "Tôi có bảo hiểm.", es: "Tengo seguro.", ro: { en: "I have insurance", ja: "hoken ga arimasu", zh: "wo you bao xian", vi: "toi co bao hiem", es: "ten-go se-gu-ro" } },

  { en: "I want to open a bank account.", ja: "口座を作りたいです。", zh: "我想开户。", vi: "Tôi muốn mở tài khoản.", es: "Quiero abrir una cuenta.", ro: { en: "I want to open a bank account", ja: "kouza o tsukuritai desu", zh: "wo xiang kai hu", vi: "toi muon mo tai khoan", es: "kye-ro a-brir u-na kwen-ta" } },
  { en: "I want to exchange money.", ja: "両替したいです。", zh: "我想换钱。", vi: "Tôi muốn đổi tiền.", es: "Quiero cambiar dinero.", ro: { en: "I want to exchange money", ja: "ryougae shitai desu", zh: "wo xiang huan qian", vi: "toi muon doi tien", es: "kye-ro kam-byar di-ne-ro" } },
  { en: "What is the exchange rate?", ja: "為替レートはいくらですか。", zh: "汇率是多少？", vi: "Tỷ giá bao nhiêu?", es: "¿Cuál es el tipo de cambio?", ro: { en: "what is the exchange rate", ja: "kawase reeto wa ikura desu ka", zh: "hui lv shi duo shao", vi: "ty gia bao nhieu", es: "kwal es el ti-po de kam-byo" } },
  { en: "Where is the ATM?", ja: "ATMはどこですか。", zh: "ATM在哪里？", vi: "Máy ATM ở đâu?", es: "¿Dónde está el cajero?", ro: { en: "where is the ATM", ja: "eeteiiemu wa doko desu ka", zh: "ATM zai na li", vi: "may ATM o dau", es: "don-de es-ta el ka-he-ro" } },
  { en: "I want to send money.", ja: "送金したいです。", zh: "我想汇款。", vi: "Tôi muốn chuyển tiền.", es: "Quiero enviar dinero.", ro: { en: "I want to send money", ja: "soukin shitai desu", zh: "wo xiang hui kuan", vi: "toi muon chuyen tien", es: "kye-ro en-vyar di-ne-ro" } },
  { en: "Do I need an alien registration card?", ja: "外国人登録証が必要ですか。", zh: "需要外国人登录证吗？", vi: "Có cần thẻ đăng ký người nước ngoài không?", es: "¿Necesito la tarjeta de registro de extranjero?", ro: { en: "do I need an alien registration card", ja: "gaikokujin tourokushou ga hitsuyou desu ka", zh: "xu yao wai guo ren deng lu zheng ma", vi: "co can the dang ky nguoi nuoc ngoai khong", es: "ne-se-si-to la tar-he-ta de re-his-tro" } },
  { en: "Please help me fill out this form.", ja: "この書類の記入を手伝ってください。", zh: "请帮我填这张表。", vi: "Giúp tôi điền mẫu đơn này.", es: "Ayúdeme a rellenar este formulario.", ro: { en: "please help me fill out this form", ja: "kono shorui no kinyuu o tetsudatte kudasai", zh: "qing bang wo tian zhe zhang biao", vi: "giup toi dien mau don nay", es: "a-yu-de-me a re-ye-nar el for-mu-la-ryo" } },
  { en: "I want to extend my visa.", ja: "ビザを延長したいです。", zh: "我想延长签证。", vi: "Tôi muốn gia hạn visa.", es: "Quiero extender mi visado.", ro: { en: "I want to extend my visa", ja: "biza o enchou shitai desu", zh: "wo xiang yan chang qian zheng", vi: "toi muon gia han visa", es: "kye-ro eks-ten-der mi vi-sa-do" } },
  { en: "Do I sign here?", ja: "ここにサインすればいいですか。", zh: "在这里签名吗？", vi: "Ký ở đây phải không?", es: "¿Firmo aquí?", ro: { en: "do I sign here", ja: "koko ni sain sureba ii desu ka", zh: "zai zhe li qian ming ma", vi: "ky o day phai khong", es: "fir-mo a-ki" } },
  { en: "Is there a fee?", ja: "手数料はかかりますか。", zh: "有手续费吗？", vi: "Có phí không?", es: "¿Hay comisión?", ro: { en: "is there a fee", ja: "tesuuryou wa kakarimasu ka", zh: "you shou xu fei ma", vi: "co phi khong", es: "ai ko-mi-syon" } },

  { en: "Do you have a room available?", ja: "空いている部屋はありますか。", zh: "有空房吗？", vi: "Còn phòng trống không?", es: "¿Tiene habitaciones disponibles?", ro: { en: "do you have a room available", ja: "aiteiru heya wa arimasu ka", zh: "you kong fang ma", vi: "con phong trong khong", es: "tye-ne a-bi-ta-syo-nes" } },
  { en: "How much per night?", ja: "一泊いくらですか。", zh: "一晚多少钱？", vi: "Một đêm bao nhiêu tiền?", es: "¿Cuánto cuesta por noche?", ro: { en: "how much per night", ja: "ippaku ikura desu ka", zh: "yi wan duo shao qian", vi: "mot dem bao nhieu tien", es: "kwan-to kwes-ta por no-che" } },
  { en: "I'd like to check in.", ja: "チェックインをお願いします。", zh: "我要办理入住。", vi: "Tôi muốn nhận phòng.", es: "Quiero hacer el check-in.", ro: { en: "I'd like to check in", ja: "chekkuin o onegaishimasu", zh: "wo yao ban li ru zhu", vi: "toi muon nhan phong", es: "kye-ro a-ser el check-in" } },
  { en: "What time is checkout?", ja: "チェックアウトは何時ですか。", zh: "几点退房？", vi: "Mấy giờ trả phòng?", es: "¿A qué hora es el checkout?", ro: { en: "what time is checkout", ja: "chekkuauto wa nanji desu ka", zh: "ji dian tui fang", vi: "may gio tra phong", es: "a ke o-ra es el check-out" } },
  { en: "What is the Wi-Fi password?", ja: "Wi-Fiのパスワードは何ですか。", zh: "Wi-Fi密码是什么？", vi: "Mật khẩu Wi-Fi là gì?", es: "¿Cuál es la contraseña del Wi-Fi?", ro: { en: "what is the wi-fi password", ja: "waifai no pasuwaado wa nan desu ka", zh: "Wi-Fi mi ma shi shen me", vi: "mat khau Wi-Fi la gi", es: "kwal es la kon-tra-se-nya del wi-fi" } },
  { en: "Can I leave my luggage here?", ja: "荷物を預けられますか。", zh: "可以寄存行李吗？", vi: "Tôi gửi hành lý được không?", es: "¿Puedo dejar mi equipaje?", ro: { en: "can I leave my luggage here", ja: "nimotsu o azukeraremasu ka", zh: "ke yi ji cun xing li ma", vi: "toi gui hanh ly duoc khong", es: "pwe-do de-har mi e-ki-pa-he" } },
  { en: "I'd like to change rooms.", ja: "部屋を変えたいです。", zh: "我想换房间。", vi: "Tôi muốn đổi phòng.", es: "Quiero cambiar de habitación.", ro: { en: "I'd like to change rooms", ja: "heya o kaetai desu", zh: "wo xiang huan fang jian", vi: "toi muon doi phong", es: "kye-ro kam-byar de a-bi-ta-syon" } },
  { en: "The air conditioner is broken.", ja: "エアコンが壊れています。", zh: "空调坏了。", vi: "Máy lạnh bị hỏng.", es: "El aire acondicionado está roto.", ro: { en: "the air conditioner is broken", ja: "eakon ga kowarete imasu", zh: "kong tiao huai le", vi: "may lanh bi hong", es: "el ai-re a-kon-di-syo-na-do es-ta ro-to" } },
  { en: "More towels, please.", ja: "タオルをもっとください。", zh: "请再给我一些毛巾。", vi: "Cho tôi thêm khăn tắm.", es: "Más toallas, por favor.", ro: { en: "more towels please", ja: "taoru o motto kudasai", zh: "qing zai gei wo yi xie mao jin", vi: "cho toi them khan tam", es: "mas to-a-yas por fa-vor" } },
  { en: "I'd like to stay one more night.", ja: "もう一泊したいです。", zh: "我想多住一晚。", vi: "Tôi muốn ở thêm một đêm.", es: "Quiero quedarme una noche más.", ro: { en: "I'd like to stay one more night", ja: "mou ippaku shitai desu", zh: "wo xiang duo zhu yi wan", vi: "toi muon o them mot dem", es: "kye-ro ke-dar-me u-na no-che mas" } },

  { en: "I'm looking for a room to rent.", ja: "部屋を探しています。", zh: "我在找房子。", vi: "Tôi đang tìm phòng thuê.", es: "Busco una habitación para alquilar.", ro: { en: "I'm looking for a room to rent", ja: "heya o sagashite imasu", zh: "wo zai zhao fang zi", vi: "toi dang tim phong thue", es: "bus-ko a-bi-ta-syon pa-ra al-ki-lar" } },
  { en: "How much is the monthly rent?", ja: "家賃は月いくらですか。", zh: "月租是多少？", vi: "Tiền thuê hàng tháng bao nhiêu?", es: "¿Cuánto es el alquiler mensual?", ro: { en: "how much is the monthly rent", ja: "yachin wa tsuki ikura desu ka", zh: "yue zu shi duo shao", vi: "tien thue hang thang bao nhieu", es: "kwan-to es el al-ki-ler men-swal" } },
  { en: "How much is the deposit?", ja: "保証金はいくらですか。", zh: "押金是多少？", vi: "Tiền đặt cọc bao nhiêu?", es: "¿Cuánto es el depósito?", ro: { en: "how much is the deposit", ja: "hoshoukin wa ikura desu ka", zh: "ya jin shi duo shao", vi: "tien dat coc bao nhieu", es: "kwan-to es el de-po-si-to" } },
  { en: "Is the maintenance fee included?", ja: "管理費は含まれていますか。", zh: "包含管理费吗？", vi: "Đã bao gồm phí quản lý chưa?", es: "¿Incluye gastos de comunidad?", ro: { en: "is the maintenance fee included", ja: "kanrihi wa fukumarete imasu ka", zh: "bao han guan li fei ma", vi: "da bao gom phi quan ly chua", es: "in-klu-ye gas-tos de ko-mu-ni-dad" } },
  { en: "I'd like to see the room.", ja: "部屋を見たいです。", zh: "我想看看房间。", vi: "Tôi muốn xem phòng.", es: "Quiero ver la habitación.", ro: { en: "I'd like to see the room", ja: "heya o mitai desu", zh: "wo xiang kan kan fang jian", vi: "toi muon xem phong", es: "kye-ro ver la a-bi-ta-syon" } },
  { en: "When can I move in?", ja: "いつ入居できますか。", zh: "什么时候可以入住？", vi: "Khi nào tôi có thể dọn vào?", es: "¿Cuándo puedo mudarme?", ro: { en: "when can I move in", ja: "itsu nyuukyo dekimasu ka", zh: "shen me shi hou ke yi ru zhu", vi: "khi nao toi co the don vao", es: "kwan-do pwe-do mu-dar-me" } },
  { en: "How long is the contract?", ja: "契約期間はどのくらいですか。", zh: "合同期是多久？", vi: "Hợp đồng bao lâu?", es: "¿Cuánto dura el contrato?", ro: { en: "how long is the contract", ja: "keiyaku kikan wa dono kurai desu ka", zh: "he tong qi shi duo jiu", vi: "hop dong bao lau", es: "kwan-to du-ra el kon-tra-to" } },
  { en: "Is it furnished?", ja: "家具付きですか。", zh: "带家具吗？", vi: "Có nội thất không?", es: "¿Está amueblado?", ro: { en: "is it furnished", ja: "kagu tsuki desu ka", zh: "dai jia ju ma", vi: "co noi that khong", es: "es-ta a-mwe-bla-do" } },
  { en: "Is it close to the subway station?", ja: "地下鉄の駅から近いですか。", zh: "离地铁站近吗？", vi: "Có gần ga tàu điện ngầm không?", es: "¿Está cerca de la estación de metro?", ro: { en: "is it close to the subway station", ja: "chikatetsu no eki kara chikai desu ka", zh: "li di tie zhan jin ma", vi: "co gan ga tau dien ngam khong", es: "es-ta ser-ka del me-tro" } },
  { en: "I want to read the contract slowly.", ja: "契約書をゆっくり読みたいです。", zh: "我想慢慢看合同。", vi: "Tôi muốn đọc kỹ hợp đồng.", es: "Quiero leer el contrato despacio.", ro: { en: "I want to read the contract slowly", ja: "keiyakusho o yukkuri yomitai desu", zh: "wo xiang man man kan he tong", vi: "toi muon doc ky hop dong", es: "kye-ro le-er el kon-tra-to des-pa-syo" } },

  { en: "I look forward to working with you.", ja: "よろしくお願いします。", zh: "请多多关照。", vi: "Mong được giúp đỡ.", es: "Espero que trabajemos bien juntos.", ro: { en: "I look forward to working with you", ja: "yoroshiku onegaishimasu", zh: "qing duo duo guan zhao", vi: "mong duoc giup do", es: "es-pe-ro ke tra-ba-he-mos hun-tos" } },
  { en: "What time is the meeting?", ja: "会議は何時ですか。", zh: "几点开会？", vi: "Cuộc họp lúc mấy giờ?", es: "¿A qué hora es la reunión?", ro: { en: "what time is the meeting", ja: "kaigi wa nanji desu ka", zh: "ji dian kai hui", vi: "cuoc hop luc may gio", es: "a ke o-ra es la re-u-nyon" } },
  { en: "May I take a short break?", ja: "少し休んでもいいですか。", zh: "我可以休息一下吗？", vi: "Tôi nghỉ một chút được không?", es: "¿Puedo descansar un momento?", ro: { en: "may I take a short break", ja: "sukoshi yasunde mo ii desu ka", zh: "wo ke yi xiu xi yi xia ma", vi: "toi nghi mot chut duoc khong", es: "pwe-do des-kan-sar un mo-men-to" } },
  { en: "Could you help me with this?", ja: "これを手伝ってもらえますか。", zh: "可以帮我做这个吗？", vi: "Bạn giúp tôi việc này được không?", es: "¿Puedes ayudarme con esto?", ro: { en: "could you help me with this", ja: "kore o tetsudatte moraemasu ka", zh: "ke yi bang wo zuo zhe ge ma", vi: "ban giup toi viec nay duoc khong", es: "pwe-des a-yu-dar-me kon es-to" } },
  { en: "When is the deadline?", ja: "いつまでに終わらせますか。", zh: "什么时候要完成？", vi: "Hạn chót là khi nào?", es: "¿Cuándo es la fecha límite?", ro: { en: "when is the deadline", ja: "itsu made ni owarasemasu ka", zh: "shen me shi hou yao wan cheng", vi: "han chot la khi nao", es: "kwan-do es la fe-cha li-mi-te" } },
  { en: "Could you explain it again?", ja: "もう一度説明してもらえますか。", zh: "可以再解释一遍吗？", vi: "Bạn giải thích lại được không?", es: "¿Puedes explicarlo otra vez?", ro: { en: "could you explain it again", ja: "mou ichido setsumei shite moraemasu ka", zh: "ke yi zai jie shi yi bian ma", vi: "ban giai thich lai duoc khong", es: "pwe-des eks-pli-kar-lo o-tra ves" } },
  { en: "Understood. I'll do it right away.", ja: "分かりました。すぐやります。", zh: "明白了，马上做。", vi: "Tôi hiểu rồi. Tôi làm ngay.", es: "Entendido. Lo hago enseguida.", ro: { en: "understood, I'll do it right away", ja: "wakarimashita, sugu yarimasu", zh: "ming bai le, ma shang zuo", vi: "toi hieu roi, toi lam ngay", es: "en-ten-di-do, lo a-go en-se-gi-da" } },
  { en: "Are we working overtime today?", ja: "今日は残業ですか。", zh: "今天加班吗？", vi: "Hôm nay có tăng ca không?", es: "¿Hoy trabajamos horas extra?", ro: { en: "are we working overtime today", ja: "kyou wa zangyou desu ka", zh: "jin tian jia ban ma", vi: "hom nay co tang ca khong", es: "oy tra-ba-ha-mos o-ras eks-tra" } },
  { en: "When is payday?", ja: "給料日はいつですか。", zh: "发工资是哪天？", vi: "Ngày lĩnh lương là khi nào?", es: "¿Cuándo es el día de pago?", ro: { en: "when is payday", ja: "kyuuryoubi wa itsu desu ka", zh: "fa gong zi shi na tian", vi: "ngay linh luong la khi nao", es: "kwan-do es el di-a de pa-go" } },
  { en: "I'd like to take a day off.", ja: "休暇を取りたいです。", zh: "我想请假。", vi: "Tôi muốn xin nghỉ phép.", es: "Quiero tomar un día libre.", ro: { en: "I'd like to take a day off", ja: "kyuuka o toritai desu", zh: "wo xiang qing jia", vi: "toi muon xin nghi phep", es: "kye-ro to-mar un di-a li-bre" } },

  { en: "It's an emergency.", ja: "緊急事態です。", zh: "情况紧急。", vi: "Đây là trường hợp khẩn cấp.", es: "Es una emergencia.", ro: { en: "it's an emergency", ja: "kinkyuu jitai desu", zh: "qing kuang jin ji", vi: "day la truong hop khan cap", es: "es u-na e-mer-hen-sya" } },
  { en: "Please call an ambulance.", ja: "救急車を呼んでください。", zh: "请叫救护车。", vi: "Vui lòng gọi xe cấp cứu.", es: "Llame a una ambulancia, por favor.", ro: { en: "please call an ambulance", ja: "kyuukyuusha o yonde kudasai", zh: "qing jiao jiu hu che", vi: "vui long goi xe cap cuu", es: "ya-me a u-na am-bu-lan-sya" } },
  { en: "There is a fire.", ja: "火事です。", zh: "着火了。", vi: "Có cháy.", es: "Hay un incendio.", ro: { en: "there is a fire", ja: "kaji desu", zh: "zhao huo le", vi: "co chay", es: "ai un in-sen-dyo" } },
  { en: "I lost my passport.", ja: "パスポートをなくしました。", zh: "我的护照丢了。", vi: "Tôi bị mất hộ chiếu.", es: "Perdí mi pasaporte.", ro: { en: "I lost my passport", ja: "pasupooto o nakushimashita", zh: "wo de hu zhao diu le", vi: "toi bi mat ho chieu", es: "per-di mi pa-sa-por-te" } },
  { en: "I was robbed.", ja: "盗まれました。", zh: "我被偷了。", vi: "Tôi bị trộm đồ.", es: "Me robaron.", ro: { en: "I was robbed", ja: "nusumaremashita", zh: "wo bei tou le", vi: "toi bi trom do", es: "me ro-ba-ron" } },
  { en: "I want to contact my embassy.", ja: "大使館に連絡したいです。", zh: "我想联系大使馆。", vi: "Tôi muốn liên hệ đại sứ quán.", es: "Quiero contactar con mi embajada.", ro: { en: "I want to contact my embassy", ja: "taishikan ni renraku shitai desu", zh: "wo xiang lian xi da shi guan", vi: "toi muon lien he dai su quan", es: "kye-ro kon-tak-tar mi em-ba-ha-da" } },
  { en: "I need a Korean interpreter.", ja: "韓国語の通訳が必要です。", zh: "我需要韩语翻译。", vi: "Tôi cần phiên dịch tiếng Hàn.", es: "Necesito un intérprete de coreano.", ro: { en: "I need a Korean interpreter", ja: "kankokugo no tsuuyaku ga hitsuyou desu", zh: "wo xu yao han yu fan yi", vi: "toi can phien dich tieng Han", es: "ne-se-si-to un in-ter-pre-te" } },
  { en: "Is it safe here?", ja: "ここは安全ですか。", zh: "这里安全吗？", vi: "Ở đây có an toàn không?", es: "¿Es seguro aquí?", ro: { en: "is it safe here", ja: "koko wa anzen desu ka", zh: "zhe li an quan ma", vi: "o day co an toan khong", es: "es se-gu-ro a-ki" } },
  { en: "Where is the police station?", ja: "警察署はどこですか。", zh: "警察局在哪里？", vi: "Đồn cảnh sát ở đâu?", es: "¿Dónde está la comisaría?", ro: { en: "where is the police station", ja: "keisatsusho wa doko desu ka", zh: "jing cha ju zai na li", vi: "don canh sat o dau", es: "don-de es-ta la ko-mi-sa-ri-a" } },
  { en: "Where is the lost and found?", ja: "忘れ物センターはどこですか。", zh: "失物招领处在哪里？", vi: "Trung tâm đồ thất lạc ở đâu?", es: "¿Dónde está la oficina de objetos perdidos?", ro: { en: "where is the lost and found", ja: "wasuremono sentaa wa doko desu ka", zh: "shi wu zhao ling chu zai na li", vi: "trung tam do that lac o dau", es: "don-de es-tan los ob-he-tos per-di-dos" } },

  { en: "What do you do on weekends?", ja: "週末は何をしますか。", zh: "周末做什么？", vi: "Cuối tuần bạn làm gì?", es: "¿Qué haces los fines de semana?", ro: { en: "what do you do on weekends", ja: "shuumatsu wa nani o shimasu ka", zh: "zhou mo zuo shen me", vi: "cuoi tuan ban lam gi", es: "ke a-ses los fi-nes de se-ma-na" } },
  { en: "What are your hobbies?", ja: "趣味は何ですか。", zh: "你的爱好是什么？", vi: "Sở thích của bạn là gì?", es: "¿Cuáles son tus aficiones?", ro: { en: "what are your hobbies", ja: "shumi wa nan desu ka", zh: "ni de ai hao shi shen me", vi: "so thich cua ban la gi", es: "kwa-les son tus a-fi-syo-nes" } },
  { en: "Do you like Korean food?", ja: "韓国料理は好きですか。", zh: "你喜欢韩国菜吗？", vi: "Bạn có thích món Hàn không?", es: "¿Te gusta la comida coreana?", ro: { en: "do you like Korean food", ja: "kankoku ryouri wa suki desu ka", zh: "ni xi huan han guo cai ma", vi: "ban co thich mon Han khong", es: "te gus-ta la ko-mi-da ko-re-a-na" } },
  { en: "What is your favorite food?", ja: "一番好きな食べ物は何ですか。", zh: "你最喜欢的食物是什么？", vi: "Món ăn bạn thích nhất là gì?", es: "¿Cuál es tu comida favorita?", ro: { en: "what is your favorite food", ja: "ichiban sukina tabemono wa nan desu ka", zh: "ni zui xi huan de shi wu shi shen me", vi: "mon an ban thich nhat la gi", es: "kwal es tu ko-mi-da fa-vo-ri-ta" } },
  { en: "Is this your first time in Korea?", ja: "韓国は初めてですか。", zh: "你是第一次来韩国吗？", vi: "Đây là lần đầu bạn đến Hàn Quốc à?", es: "¿Es tu primera vez en Corea?", ro: { en: "is this your first time in Korea", ja: "kankoku wa hajimete desu ka", zh: "ni shi di yi ci lai han guo ma", vi: "day la lan dau ban den Han Quoc a", es: "es tu pri-me-ra ves en ko-re-a" } },
  { en: "Shall I take a photo for you?", ja: "写真をお撮りしましょうか。", zh: "我帮你拍照吧？", vi: "Tôi chụp ảnh giúp bạn nhé?", es: "¿Te tomo una foto?", ro: { en: "shall I take a photo for you", ja: "shashin o otori shimashou ka", zh: "wo bang ni pai zhao ba", vi: "toi chup anh giup ban nhe", es: "te to-mo u-na fo-to" } },
  { en: "Let's exchange contact information.", ja: "連絡先を交換しましょう。", zh: "我们交换联系方式吧。", vi: "Chúng ta trao đổi liên lạc nhé.", es: "Intercambiemos contactos.", ro: { en: "let's exchange contact information", ja: "renrakusaki o koukan shimashou", zh: "wo men jiao huan lian xi fang shi ba", vi: "chung ta trao doi lien lac nhe", es: "in-ter-kam-bye-mos kon-tak-tos" } },
  { en: "Let's eat together next time.", ja: "今度一緒に食事しましょう。", zh: "下次一起吃饭吧。", vi: "Lần sau cùng ăn nhé.", es: "Comamos juntos la próxima vez.", ro: { en: "let's eat together next time", ja: "kondo issho ni shokuji shimashou", zh: "xia ci yi qi chi fan ba", vi: "lan sau cung an nhe", es: "ko-ma-mos hun-tos la prok-si-ma ves" } },
  { en: "How is life in Korea?", ja: "韓国での生活はどうですか。", zh: "在韩国生活怎么样？", vi: "Cuộc sống ở Hàn thế nào?", es: "¿Qué tal la vida en Corea?", ro: { en: "how is life in Korea", ja: "kankoku de no seikatsu wa dou desu ka", zh: "zai han guo sheng huo zen me yang", vi: "cuoc song o Han the nao", es: "ke tal la vi-da en ko-re-a" } },
  { en: "It was nice meeting you.", ja: "お会いできてうれしかったです。", zh: "很高兴见到你。", vi: "Rất vui được gặp bạn.", es: "Fue un placer conocerte.", ro: { en: "it was nice meeting you", ja: "oai dekite ureshikatta desu", zh: "hen gao xing jian dao ni", vi: "rat vui duoc gap ban", es: "fwe un pla-ser ko-no-ser-te" } }
];

window.WIIINFO_MULTI_PHRASES = (window.THAI_PHRASES || []).map((phrase, index) => {
  const extra = window.WIIINFO_EXTRA_PHRASES[index] || {};
  return {
    ...phrase,
    en: extra.en || "",
    ja: extra.ja || "",
    zh: extra.zh || "",
    vi: extra.vi || "",
    es: extra.es || "",
    roByLang: extra.ro || {}
  };
});

// 구 데이터(견본 8자)는 2026-06-04 히라가나·가타카나 전체 92자로 확장하며 교체됨 (git 이력에 보존)
window.JAPANESE_LETTERS = [
  { type: "히라가나", char: "あ", name: "a", sound: "a · 아", example: "あい(ai) 사랑", tts: "あ" },
  { type: "히라가나", char: "い", name: "i", sound: "i · 이", example: "いぬ(inu) 개", tts: "い" },
  { type: "히라가나", char: "う", name: "u", sound: "u · 우", example: "うみ(umi) 바다", tts: "う" },
  { type: "히라가나", char: "え", name: "e", sound: "e · 에", example: "えき(eki) 역", tts: "え" },
  { type: "히라가나", char: "お", name: "o", sound: "o · 오", example: "おちゃ(ocha) 차", tts: "お" },
  { type: "히라가나", char: "か", name: "ka", sound: "ka · 카", example: "かさ(kasa) 우산", tts: "か" },
  { type: "히라가나", char: "き", name: "ki", sound: "ki · 키", example: "き(ki) 나무", tts: "き" },
  { type: "히라가나", char: "く", name: "ku", sound: "ku · 쿠", example: "くつ(kutsu) 신발", tts: "く" },
  { type: "히라가나", char: "け", name: "ke", sound: "ke · 케", example: "けさ(kesa) 오늘 아침", tts: "け" },
  { type: "히라가나", char: "こ", name: "ko", sound: "ko · 코", example: "こども(kodomo) 아이", tts: "こ" },
  { type: "히라가나", char: "さ", name: "sa", sound: "sa · 사", example: "さかな(sakana) 생선", tts: "さ" },
  { type: "히라가나", char: "し", name: "shi", sound: "shi · 시", example: "しお(shio) 소금", tts: "し" },
  { type: "히라가나", char: "す", name: "su", sound: "su · 스", example: "すし(sushi) 초밥", tts: "す" },
  { type: "히라가나", char: "せ", name: "se", sound: "se · 세", example: "せかい(sekai) 세계", tts: "せ" },
  { type: "히라가나", char: "そ", name: "so", sound: "so · 소", example: "そら(sora) 하늘", tts: "そ" },
  { type: "히라가나", char: "た", name: "ta", sound: "ta · 타", example: "たまご(tamago) 달걀", tts: "た" },
  { type: "히라가나", char: "ち", name: "chi", sound: "chi · 치", example: "ちず(chizu) 지도", tts: "ち" },
  { type: "히라가나", char: "つ", name: "tsu", sound: "tsu · 츠", example: "つき(tsuki) 달", tts: "つ" },
  { type: "히라가나", char: "て", name: "te", sound: "te · 테", example: "て(te) 손", tts: "て" },
  { type: "히라가나", char: "と", name: "to", sound: "to · 토", example: "とり(tori) 새", tts: "と" },
  { type: "히라가나", char: "な", name: "na", sound: "na · 나", example: "なつ(natsu) 여름", tts: "な" },
  { type: "히라가나", char: "に", name: "ni", sound: "ni · 니", example: "にく(niku) 고기", tts: "に" },
  { type: "히라가나", char: "ぬ", name: "nu", sound: "nu · 누", example: "ぬの(nuno) 천", tts: "ぬ" },
  { type: "히라가나", char: "ね", name: "ne", sound: "ne · 네", example: "ねこ(neko) 고양이", tts: "ね" },
  { type: "히라가나", char: "の", name: "no", sound: "no · 노", example: "のみもの(nomimono) 음료", tts: "の" },
  { type: "히라가나", char: "は", name: "ha", sound: "ha · 하", example: "はな(hana) 꽃", tts: "は" },
  { type: "히라가나", char: "ひ", name: "hi", sound: "hi · 히", example: "ひと(hito) 사람", tts: "ひ" },
  { type: "히라가나", char: "ふ", name: "fu", sound: "fu · 후", example: "ふゆ(fuyu) 겨울", tts: "ふ" },
  { type: "히라가나", char: "へ", name: "he", sound: "he · 헤", example: "へや(heya) 방", tts: "へ" },
  { type: "히라가나", char: "ほ", name: "ho", sound: "ho · 호", example: "ほん(hon) 책", tts: "ほ" },
  { type: "히라가나", char: "ま", name: "ma", sound: "ma · 마", example: "まち(machi) 거리", tts: "ま" },
  { type: "히라가나", char: "み", name: "mi", sound: "mi · 미", example: "みず(mizu) 물", tts: "み" },
  { type: "히라가나", char: "む", name: "mu", sound: "mu · 무", example: "むし(mushi) 벌레", tts: "む" },
  { type: "히라가나", char: "め", name: "me", sound: "me · 메", example: "め(me) 눈", tts: "め" },
  { type: "히라가나", char: "も", name: "mo", sound: "mo · 모", example: "もも(momo) 복숭아", tts: "も" },
  { type: "히라가나", char: "や", name: "ya", sound: "ya · 야", example: "やま(yama) 산", tts: "や" },
  { type: "히라가나", char: "ゆ", name: "yu", sound: "yu · 유", example: "ゆき(yuki) 눈(雪)", tts: "ゆ" },
  { type: "히라가나", char: "よ", name: "yo", sound: "yo · 요", example: "よる(yoru) 밤", tts: "よ" },
  { type: "히라가나", char: "ら", name: "ra", sound: "ra · 라", example: "らいねん(rainen) 내년", tts: "ら" },
  { type: "히라가나", char: "り", name: "ri", sound: "ri · 리", example: "りんご(ringo) 사과", tts: "り" },
  { type: "히라가나", char: "る", name: "ru", sound: "ru · 루", example: "るす(rusu) 부재중", tts: "る" },
  { type: "히라가나", char: "れ", name: "re", sound: "re · 레", example: "れきし(rekishi) 역사", tts: "れ" },
  { type: "히라가나", char: "ろ", name: "ro", sound: "ro · 로", example: "ろうそく(rousoku) 양초", tts: "ろ" },
  { type: "히라가나", char: "わ", name: "wa", sound: "wa · 와", example: "わたし(watashi) 나", tts: "わ" },
  { type: "히라가나", char: "を", name: "o(wo)", sound: "o · 오 (조사 전용)", example: "ほんをよむ 책을 읽다", tts: "を" },
  { type: "히라가나", char: "ん", name: "n", sound: "n · 응(받침)", example: "みかん(mikan) 귤", tts: "ん" },
  { type: "가타카나", char: "ア", name: "a", sound: "a · 아", example: "アジア(ajia) 아시아", tts: "ア" },
  { type: "가타카나", char: "イ", name: "i", sound: "i · 이", example: "インク(inku) 잉크", tts: "イ" },
  { type: "가타카나", char: "ウ", name: "u", sound: "u · 우", example: "ウール(uuru) 울", tts: "ウ" },
  { type: "가타카나", char: "エ", name: "e", sound: "e · 에", example: "エアコン(eakon) 에어컨", tts: "エ" },
  { type: "가타카나", char: "オ", name: "o", sound: "o · 오", example: "オレンジ(orenji) 오렌지", tts: "オ" },
  { type: "가타카나", char: "カ", name: "ka", sound: "ka · 카", example: "カード(kaado) 카드", tts: "カ" },
  { type: "가타카나", char: "キ", name: "ki", sound: "ki · 키", example: "キムチ(kimuchi) 김치", tts: "キ" },
  { type: "가타카나", char: "ク", name: "ku", sound: "ku · 쿠", example: "クラス(kurasu) 클래스", tts: "ク" },
  { type: "가타카나", char: "ケ", name: "ke", sound: "ke · 케", example: "ケーキ(keeki) 케이크", tts: "ケ" },
  { type: "가타카나", char: "コ", name: "ko", sound: "ko · 코", example: "コーヒー(koohii) 커피", tts: "コ" },
  { type: "가타카나", char: "サ", name: "sa", sound: "sa · 사", example: "サラダ(sarada) 샐러드", tts: "サ" },
  { type: "가타카나", char: "シ", name: "shi", sound: "shi · 시", example: "シャツ(shatsu) 셔츠", tts: "シ" },
  { type: "가타카나", char: "ス", name: "su", sound: "su · 스", example: "スポーツ(supootsu) 스포츠", tts: "ス" },
  { type: "가타카나", char: "セ", name: "se", sound: "se · 세", example: "セール(seeru) 세일", tts: "セ" },
  { type: "가타카나", char: "ソ", name: "so", sound: "so · 소", example: "ソース(soosu) 소스", tts: "ソ" },
  { type: "가타카나", char: "タ", name: "ta", sound: "ta · 타", example: "タクシー(takushii) 택시", tts: "タ" },
  { type: "가타카나", char: "チ", name: "chi", sound: "chi · 치", example: "チケット(chiketto) 티켓", tts: "チ" },
  { type: "가타카나", char: "ツ", name: "tsu", sound: "tsu · 츠", example: "ツアー(tsuaa) 투어", tts: "ツ" },
  { type: "가타카나", char: "テ", name: "te", sound: "te · 테", example: "テレビ(terebi) TV", tts: "テ" },
  { type: "가타카나", char: "ト", name: "to", sound: "to · 토", example: "トマト(tomato) 토마토", tts: "ト" },
  { type: "가타카나", char: "ナ", name: "na", sound: "na · 나", example: "ナイフ(naifu) 나이프", tts: "ナ" },
  { type: "가타카나", char: "ニ", name: "ni", sound: "ni · 니", example: "ニュース(nyuusu) 뉴스", tts: "ニ" },
  { type: "가타카나", char: "ヌ", name: "nu", sound: "nu · 누", example: "ヌードル(nuudoru) 누들", tts: "ヌ" },
  { type: "가타카나", char: "ネ", name: "ne", sound: "ne · 네", example: "ネクタイ(nekutai) 넥타이", tts: "ネ" },
  { type: "가타카나", char: "ノ", name: "no", sound: "no · 노", example: "ノート(nooto) 노트", tts: "ノ" },
  { type: "가타카나", char: "ハ", name: "ha", sound: "ha · 하", example: "ハンバーガー 햄버거", tts: "ハ" },
  { type: "가타카나", char: "ヒ", name: "hi", sound: "hi · 히", example: "ヒーター(hiitaa) 히터", tts: "ヒ" },
  { type: "가타카나", char: "フ", name: "fu", sound: "fu · 후", example: "フランス(furansu) 프랑스", tts: "フ" },
  { type: "가타카나", char: "ヘ", name: "he", sound: "he · 헤", example: "ヘリコプター 헬리콥터", tts: "ヘ" },
  { type: "가타카나", char: "ホ", name: "ho", sound: "ho · 호", example: "ホテル(hoteru) 호텔", tts: "ホ" },
  { type: "가타카나", char: "マ", name: "ma", sound: "ma · 마", example: "マスク(masuku) 마스크", tts: "マ" },
  { type: "가타카나", char: "ミ", name: "mi", sound: "mi · 미", example: "ミルク(miruku) 밀크", tts: "ミ" },
  { type: "가타카나", char: "ム", name: "mu", sound: "mu · 무", example: "ムード(muudo) 무드", tts: "ム" },
  { type: "가타카나", char: "メ", name: "me", sound: "me · 메", example: "メール(meeru) 메일", tts: "メ" },
  { type: "가타카나", char: "モ", name: "mo", sound: "mo · 모", example: "モデル(moderu) 모델", tts: "モ" },
  { type: "가타카나", char: "ヤ", name: "ya", sound: "ya · 야", example: "タイヤ(taiya) 타이어", tts: "ヤ" },
  { type: "가타카나", char: "ユ", name: "yu", sound: "yu · 유", example: "ユーモア(yuumoa) 유머", tts: "ユ" },
  { type: "가타카나", char: "ヨ", name: "yo", sound: "yo · 요", example: "ヨーグルト 요구르트", tts: "ヨ" },
  { type: "가타카나", char: "ラ", name: "ra", sound: "ra · 라", example: "ラーメン(raamen) 라멘", tts: "ラ" },
  { type: "가타카나", char: "リ", name: "ri", sound: "ri · 리", example: "リスト(risuto) 리스트", tts: "リ" },
  { type: "가타카나", char: "ル", name: "ru", sound: "ru · 루", example: "ルール(ruuru) 룰", tts: "ル" },
  { type: "가타카나", char: "レ", name: "re", sound: "re · 레", example: "レストラン 레스토랑", tts: "レ" },
  { type: "가타카나", char: "ロ", name: "ro", sound: "ro · 로", example: "ロボット(robotto) 로봇", tts: "ロ" },
  { type: "가타카나", char: "ワ", name: "wa", sound: "wa · 와", example: "ワイン(wain) 와인", tts: "ワ" },
  { type: "가타카나", char: "ヲ", name: "o(wo)", sound: "o · 오 (표기용)", example: "조사 표기에 사용", tts: "ヲ" },
  { type: "가타카나", char: "ン", name: "n", sound: "n · 응(받침)", example: "パン(pan) 빵", tts: "ン" }
];

window.ENGLISH_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((char, index) => ({
  type: "알파벳",
  char,
  name: char.toLowerCase(),
  sound: `${char.toLowerCase()} · 영어 알파벳 ${index + 1}`,
  example: `${char} word`
}));

// 구 데이터(견본 6자)는 2026-06-04 성조 5종 + 기초 한자 25자로 확장하며 교체됨 (git 이력에 보존)
window.CHINESE_LETTERS = [
  { type: "성조", char: "ā", name: "1성 (第一声)", sound: "높고 평평한 소리", example: "mā 妈 엄마", tts: "妈" },
  { type: "성조", char: "á", name: "2성 (第二声)", sound: "올라가는 소리", example: "má 麻 삼", tts: "麻" },
  { type: "성조", char: "ǎ", name: "3성 (第三声)", sound: "낮아졌다 올라가는 소리", example: "mǎ 马 말", tts: "马" },
  { type: "성조", char: "à", name: "4성 (第四声)", sound: "강하게 내려가는 소리", example: "mà 骂 꾸짖다", tts: "骂" },
  { type: "성조", char: "a", name: "경성 (轻声)", sound: "짧고 가볍게", example: "ma 吗 의문조사", tts: "吗" },
  { type: "기초 한자", char: "你", name: "nǐ", sound: "니 · 너/당신", example: "你好 안녕하세요", tts: "你" },
  { type: "기초 한자", char: "好", name: "hǎo", sound: "하오 · 좋다", example: "很好 아주 좋다", tts: "好" },
  { type: "기초 한자", char: "我", name: "wǒ", sound: "워 · 나", example: "我是 저는 ~입니다", tts: "我" },
  { type: "기초 한자", char: "是", name: "shì", sound: "스 · ~이다", example: "是的 맞습니다", tts: "是" },
  { type: "기초 한자", char: "不", name: "bù", sound: "뿌 · 아니다", example: "不是 아닙니다", tts: "不" },
  { type: "기초 한자", char: "在", name: "zài", sound: "짜이 · ~에 있다", example: "在哪里 어디에 있나요", tts: "在" },
  { type: "기초 한자", char: "有", name: "yǒu", sound: "여우 · 있다", example: "有没有 있나요 없나요", tts: "有" },
  { type: "기초 한자", char: "人", name: "rén", sound: "런 · 사람", example: "韩国人 한국인", tts: "人" },
  { type: "기초 한자", char: "大", name: "dà", sound: "따 · 크다", example: "大小 크기", tts: "大" },
  { type: "기초 한자", char: "小", name: "xiǎo", sound: "샤오 · 작다", example: "小时 시간", tts: "小" },
  { type: "기초 한자", char: "上", name: "shàng", sound: "샹 · 위", example: "上面 위쪽", tts: "上" },
  { type: "기초 한자", char: "下", name: "xià", sound: "샤 · 아래", example: "下面 아래쪽", tts: "下" },
  { type: "기초 한자", char: "中", name: "zhōng", sound: "쭝 · 가운데", example: "中国 중국", tts: "中" },
  { type: "기초 한자", char: "国", name: "guó", sound: "궈 · 나라", example: "韩国 한국", tts: "国" },
  { type: "기초 한자", char: "水", name: "shuǐ", sound: "쉐이 · 물", example: "喝水 물을 마시다", tts: "水" },
  { type: "기초 한자", char: "火", name: "huǒ", sound: "훠 · 불", example: "火车 기차", tts: "火" },
  { type: "기초 한자", char: "山", name: "shān", sound: "샨 · 산", example: "登山 등산", tts: "山" },
  { type: "기초 한자", char: "口", name: "kǒu", sound: "커우 · 입", example: "入口 입구", tts: "口" },
  { type: "기초 한자", char: "手", name: "shǒu", sound: "셔우 · 손", example: "手机 휴대폰", tts: "手" },
  { type: "기초 한자", char: "日", name: "rì", sound: "르 · 해/일", example: "生日 생일", tts: "日" },
  { type: "기초 한자", char: "月", name: "yuè", sound: "위에 · 달/월", example: "一个月 한 달", tts: "月" },
  { type: "기초 한자", char: "年", name: "nián", sound: "니엔 · 년", example: "今年 올해", tts: "年" },
  { type: "기초 한자", char: "钱", name: "qián", sound: "치엔 · 돈", example: "多少钱 얼마예요", tts: "钱" },
  { type: "기초 한자", char: "吃", name: "chī", sound: "츠 · 먹다", example: "吃饭 밥을 먹다", tts: "吃" },
  { type: "기초 한자", char: "去", name: "qù", sound: "취 · 가다", example: "去哪儿 어디 가세요", tts: "去" }
];

// 구 데이터(견본 6자)는 2026-06-04 알파벳 29자 + 성조 6종으로 확장하며 교체됨 (git 이력에 보존)
window.VIETNAMESE_LETTERS = [
  { type: "알파벳", char: "a", name: "a", sound: "아", example: "ba 셋/아빠", tts: "a" },
  { type: "알파벳", char: "ă", name: "á", sound: "짧은 아", example: "ăn 먹다", tts: "ăn" },
  { type: "알파벳", char: "â", name: "ớ", sound: "어(짧게)", example: "âm 소리", tts: "âm" },
  { type: "알파벳", char: "b", name: "bê", sound: "ㅂ · b", example: "bạn 친구", tts: "bê" },
  { type: "알파벳", char: "c", name: "xê", sound: "ㄲ · k", example: "cá 생선", tts: "xê" },
  { type: "알파벳", char: "d", name: "dê", sound: "ㅈ/z (북부)", example: "da 피부", tts: "dê" },
  { type: "알파벳", char: "đ", name: "đê", sound: "ㄷ · d", example: "đi 가다", tts: "đê" },
  { type: "알파벳", char: "e", name: "e", sound: "애", example: "em 동생", tts: "e" },
  { type: "알파벳", char: "ê", name: "ê", sound: "에", example: "đêm 밤", tts: "ê" },
  { type: "알파벳", char: "g", name: "giê", sound: "ㄱ · g", example: "gà 닭", tts: "giê" },
  { type: "알파벳", char: "h", name: "hát", sound: "ㅎ · h", example: "hoa 꽃", tts: "hát" },
  { type: "알파벳", char: "i", name: "i ngắn", sound: "이(짧게)", example: "đi 가다", tts: "i" },
  { type: "알파벳", char: "k", name: "ca", sound: "ㄲ · k", example: "kem 아이스크림", tts: "ca" },
  { type: "알파벳", char: "l", name: "e-lờ", sound: "ㄹ · l", example: "làm 하다", tts: "lờ" },
  { type: "알파벳", char: "m", name: "em-mờ", sound: "ㅁ · m", example: "mẹ 엄마", tts: "mờ" },
  { type: "알파벳", char: "n", name: "en-nờ", sound: "ㄴ · n", example: "nước 물/나라", tts: "nờ" },
  { type: "알파벳", char: "o", name: "o", sound: "어(입 크게)", example: "to 크다", tts: "o" },
  { type: "알파벳", char: "ô", name: "ô", sound: "오", example: "ông 할아버지", tts: "ô" },
  { type: "알파벳", char: "ơ", name: "ơ", sound: "어", example: "cơm 밥", tts: "ơ" },
  { type: "알파벳", char: "p", name: "pê", sound: "ㅃ · p", example: "pin 배터리", tts: "pê" },
  { type: "알파벳", char: "q", name: "quy", sound: "꾸 · qu", example: "quê 고향", tts: "quy" },
  { type: "알파벳", char: "r", name: "e-rờ", sound: "ㅈ/r", example: "rau 채소", tts: "rờ" },
  { type: "알파벳", char: "s", name: "ét-xì", sound: "ㅅ · s", example: "sông 강", tts: "ét xì" },
  { type: "알파벳", char: "t", name: "tê", sound: "ㄸ · t", example: "tay 손", tts: "tê" },
  { type: "알파벳", char: "u", name: "u", sound: "우", example: "mua 사다", tts: "u" },
  { type: "알파벳", char: "ư", name: "ư", sound: "으", example: "thư 편지", tts: "ư" },
  { type: "알파벳", char: "v", name: "vê", sound: "ㅂ/v", example: "về 돌아가다", tts: "vê" },
  { type: "알파벳", char: "x", name: "ích-xì", sound: "ㅆ · s", example: "xe 차", tts: "ích xì" },
  { type: "알파벳", char: "y", name: "i dài", sound: "이(길게)", example: "yêu 사랑하다", tts: "i dài" },
  { type: "성조", char: "a", name: "ngang (평성)", sound: "평평하게", example: "ma 귀신", tts: "ma" },
  { type: "성조", char: "á", name: "sắc", sound: "올라가는 성조", example: "má 볼/엄마", tts: "má" },
  { type: "성조", char: "à", name: "huyền", sound: "내려가는 성조", example: "mà 그런데", tts: "mà" },
  { type: "성조", char: "ả", name: "hỏi", sound: "내려갔다 올라가는 성조", example: "mả 무덤", tts: "mả" },
  { type: "성조", char: "ã", name: "ngã", sound: "꺾이는 성조", example: "mã 말(馬)", tts: "mã" },
  { type: "성조", char: "ạ", name: "nặng", sound: "짧고 무겁게 떨어지는 성조", example: "mạ 모(벼)", tts: "mạ" }
];

// 구 데이터(견본 6자)는 2026-06-04 스페인어 알파벳 전체 27자로 확장하며 교체됨 (git 이력에 보존)
window.SPANISH_LETTERS = [
  { type: "알파벳", char: "A", name: "a", sound: "아", example: "agua 물", tts: "a" },
  { type: "알파벳", char: "B", name: "be", sound: "베", example: "banco 은행", tts: "be" },
  { type: "알파벳", char: "C", name: "ce", sound: "세/께", example: "casa 집", tts: "ce" },
  { type: "알파벳", char: "D", name: "de", sound: "데", example: "día 날/하루", tts: "de" },
  { type: "알파벳", char: "E", name: "e", sound: "에", example: "español 스페인어", tts: "e" },
  { type: "알파벳", char: "F", name: "efe", sound: "에페", example: "familia 가족", tts: "efe" },
  { type: "알파벳", char: "G", name: "ge", sound: "헤/게", example: "gracias 감사합니다", tts: "ge" },
  { type: "알파벳", char: "H", name: "hache", sound: "아체 (묵음)", example: "hola 안녕하세요", tts: "hache" },
  { type: "알파벳", char: "I", name: "i", sound: "이", example: "isla 섬", tts: "i" },
  { type: "알파벳", char: "J", name: "jota", sound: "호타 · ㅎ", example: "jardín 정원", tts: "jota" },
  { type: "알파벳", char: "K", name: "ka", sound: "까", example: "kilo 킬로", tts: "ka" },
  { type: "알파벳", char: "L", name: "ele", sound: "엘레", example: "luna 달", tts: "ele" },
  { type: "알파벳", char: "M", name: "eme", sound: "에메", example: "mesa 탁자", tts: "eme" },
  { type: "알파벳", char: "N", name: "ene", sound: "에네", example: "noche 밤", tts: "ene" },
  { type: "알파벳", char: "Ñ", name: "eñe", sound: "에녜 · 니", example: "España 스페인", tts: "eñe" },
  { type: "알파벳", char: "O", name: "o", sound: "오", example: "oro 금", tts: "o" },
  { type: "알파벳", char: "P", name: "pe", sound: "뻬", example: "pan 빵", tts: "pe" },
  { type: "알파벳", char: "Q", name: "cu", sound: "꾸", example: "queso 치즈", tts: "cu" },
  { type: "알파벳", char: "R", name: "erre", sound: "에레 (혀 굴림)", example: "rojo 빨강", tts: "erre" },
  { type: "알파벳", char: "S", name: "ese", sound: "에세", example: "sol 해", tts: "ese" },
  { type: "알파벳", char: "T", name: "te", sound: "떼", example: "tiempo 시간/날씨", tts: "te" },
  { type: "알파벳", char: "U", name: "u", sound: "우", example: "uno 하나", tts: "u" },
  { type: "알파벳", char: "V", name: "uve", sound: "우베 (b와 동일)", example: "vino 와인", tts: "uve" },
  { type: "알파벳", char: "W", name: "uve doble", sound: "우베 도블레", example: "web 웹", tts: "uve doble" },
  { type: "알파벳", char: "X", name: "equis", sound: "에끼스", example: "taxi 택시", tts: "equis" },
  { type: "알파벳", char: "Y", name: "ye", sound: "예", example: "yo 나", tts: "ye" },
  { type: "알파벳", char: "Z", name: "zeta", sound: "세타", example: "zapato 신발", tts: "zeta" }
];