window.THAI_PHRASES = [
  { c: "인사", ko: "안녕하세요.", th: "สวัสดีครับ", ro: "sa-wat-dee khrab" },
  { c: "인사", ko: "안녕하세요. 만나서 반갑습니다.", th: "สวัสดีครับ ยินดีที่ได้รู้จักครับ", ro: "sa-wat-dee khrab, yin-dee thee dai roo-jak khrab" },
  { c: "인사", ko: "감사합니다.", th: "ขอบคุณครับ", ro: "khop khun khrab" },
  { c: "인사", ko: "정말 감사합니다.", th: "ขอบคุณมากครับ", ro: "khop khun maak khrab" },
  { c: "인사", ko: "죄송합니다.", th: "ขอโทษครับ", ro: "khor thot khrab" },
  { c: "인사", ko: "괜찮습니다.", th: "ไม่เป็นไรครับ", ro: "mai pen rai khrab" },
  { c: "인사", ko: "잘 지내세요?", th: "สบายดีไหมครับ", ro: "sa-baai dee mai khrab" },
  { c: "인사", ko: "잘 지냅니다.", th: "สบายดีครับ", ro: "sa-baai dee khrab" },
  { c: "인사", ko: "또 만나요.", th: "แล้วพบกันใหม่ครับ", ro: "laeo phop gan mai khrab" },
  { c: "인사", ko: "안녕히 가세요.", th: "ลาก่อนครับ", ro: "laa gon khrab" },

  { c: "자기소개", ko: "저는 한국 사람입니다.", th: "ผมเป็นคนเกาหลี", ro: "phom pen khon gao-lee" },
  { c: "자기소개", ko: "저는 한국에서 왔습니다.", th: "ผมมาจากเกาหลี", ro: "phom maa jaak gao-lee" },
  { c: "자기소개", ko: "제 이름은 ___입니다.", th: "ผมชื่อ ___", ro: "phom chue ___" },
  { c: "자기소개", ko: "당신의 이름은 무엇입니까?", th: "คุณชื่ออะไรครับ", ro: "khun chue a-rai khrab" },
  { c: "자기소개", ko: "저는 태국어를 배우고 있습니다.", th: "ผมกำลังเรียนภาษาไทย", ro: "phom gam-lang rian phaa-saa thai" },
  { c: "자기소개", ko: "태국어를 조금 할 수 있습니다.", th: "ผมพูดภาษาไทยได้นิดหน่อย", ro: "phom phoot phaa-saa thai dai nit noi" },
  { c: "자기소개", ko: "저는 영어를 조금 할 수 있습니다.", th: "ผมพูดภาษาอังกฤษได้นิดหน่อย", ro: "phom phoot phaa-saa ang-grit dai nit noi" },
  { c: "자기소개", ko: "저는 이해했습니다.", th: "ผมเข้าใจแล้วครับ", ro: "phom khao jai laeo khrab" },
  { c: "자기소개", ko: "저는 이해하지 못했습니다.", th: "ผมไม่เข้าใจครับ", ro: "phom mai khao jai khrab" },
  { c: "자기소개", ko: "천천히 말씀해 주세요.", th: "กรุณาพูดช้า ๆ ครับ", ro: "ga-ru-naa phoot chaa chaa khrab" },

  { c: "기초응답", ko: "네.", th: "ใช่ครับ", ro: "chai khrab" },
  { c: "기초응답", ko: "아니요.", th: "ไม่ใช่ครับ", ro: "mai chai khrab" },
  { c: "기초응답", ko: "맞습니다.", th: "ถูกต้องครับ", ro: "thook tong khrab" },
  { c: "기초응답", ko: "아닙니다.", th: "ไม่ถูกครับ", ro: "mai thook khrab" },
  { c: "기초응답", ko: "좋습니다.", th: "ดีครับ", ro: "dee khrab" },
  { c: "기초응답", ko: "좋지 않습니다.", th: "ไม่ดีครับ", ro: "mai dee khrab" },
  { c: "기초응답", ko: "괜찮아요?", th: "โอเคไหมครับ", ro: "oh-kay mai khrab" },
  { c: "기초응답", ko: "괜찮아요.", th: "โอเคครับ", ro: "oh-kay khrab" },
  { c: "기초응답", ko: "문제 없습니다.", th: "ไม่มีปัญหาครับ", ro: "mai mee pan-haa khrab" },
  { c: "기초응답", ko: "다시 말해 주세요.", th: "กรุณาพูดอีกครั้งครับ", ro: "ga-ru-naa phoot eek khrang khrab" },

  { c: "숫자/시간", ko: "이것은 얼마입니까?", th: "อันนี้ราคาเท่าไหร่ครับ", ro: "an nee raa-khaa thao-rai khrab" },
  { c: "숫자/시간", ko: "너무 비쌉니다.", th: "แพงเกินไปครับ", ro: "phaeng gern pai khrab" },
  { c: "숫자/시간", ko: "조금 깎아 주세요.", th: "ลดราคาให้หน่อยครับ", ro: "lot raa-khaa hai noi khrab" },
  { c: "숫자/시간", ko: "몇 시입니까?", th: "กี่โมงครับ", ro: "gee mohng khrab" },
  { c: "숫자/시간", ko: "오늘입니다.", th: "วันนี้ครับ", ro: "wan nee khrab" },
  { c: "숫자/시간", ko: "내일입니다.", th: "พรุ่งนี้ครับ", ro: "phrung nee khrab" },
  { c: "숫자/시간", ko: "어제입니다.", th: "เมื่อวานครับ", ro: "muea waan khrab" },
  { c: "숫자/시간", ko: "지금 가겠습니다.", th: "ผมจะไปตอนนี้ครับ", ro: "phom ja pai ton nee khrab" },
  { c: "숫자/시간", ko: "잠시만 기다려 주세요.", th: "กรุณารอสักครู่ครับ", ro: "ga-ru-naa ror sak khroo khrab" },
  { c: "숫자/시간", ko: "10분 정도 걸립니다.", th: "ใช้เวลาประมาณสิบนาทีครับ", ro: "chai way-laa pra-maan sip naa-thee khrab" },

  { c: "이동", ko: "여기는 어디입니까?", th: "ที่นี่ที่ไหนครับ", ro: "thee nee thee nai khrab" },
  { c: "이동", ko: "화장실은 어디입니까?", th: "ห้องน้ำอยู่ที่ไหนครับ", ro: "hong naam yuu thee nai khrab" },
  { c: "이동", ko: "지하철역은 어디입니까?", th: "สถานีรถไฟใต้ดินอยู่ที่ไหนครับ", ro: "sa-thaa-nee rot-fai dtai-din yuu thee nai khrab" },
  { c: "이동", ko: "이쪽으로 오세요.", th: "เชิญทางนี้ครับ", ro: "choen thaang nee khrab" },
  { c: "이동", ko: "저쪽으로 가세요.", th: "ไปทางนั้นครับ", ro: "pai thaang nan khrab" },
  { c: "이동", ko: "오른쪽으로 가세요.", th: "ไปทางขวาครับ", ro: "pai thaang khwaa khrab" },
  { c: "이동", ko: "왼쪽으로 가세요.", th: "ไปทางซ้ายครับ", ro: "pai thaang saai khrab" },
  { c: "이동", ko: "곧장 가세요.", th: "ตรงไปครับ", ro: "dtrong pai khrab" },
  { c: "이동", ko: "택시를 타고 싶습니다.", th: "ผมอยากนั่งแท็กซี่ครับ", ro: "phom yaak nang taxi khrab" },
  { c: "이동", ko: "여기서 내려 주세요.", th: "จอดตรงนี้ครับ", ro: "jot dtrong nee khrab" },

  { c: "식당", ko: "메뉴 주세요.", th: "ขอเมนูหน่อยครับ", ro: "khor menu noi khrab" },
  { c: "식당", ko: "이것을 주세요.", th: "ขออันนี้ครับ", ro: "khor an nee khrab" },
  { c: "식당", ko: "물을 주세요.", th: "ขอน้ำหน่อยครับ", ro: "khor naam noi khrab" },
  { c: "식당", ko: "맵지 않게 해 주세요.", th: "ขอไม่เผ็ดครับ", ro: "khor mai phet khrab" },
  { c: "식당", ko: "조금 맵게 해 주세요.", th: "ขอเผ็ดนิดหน่อยครับ", ro: "khor phet nit noi khrab" },
  { c: "식당", ko: "맛있습니다.", th: "อร่อยครับ", ro: "a-roi khrab" },
  { c: "식당", ko: "계산해 주세요.", th: "เช็กบิลด้วยครับ", ro: "check bin duai khrab" },
  { c: "식당", ko: "포장해 주세요.", th: "ใส่ถุงกลับบ้านครับ", ro: "sai thung glap baan khrab" },
  { c: "식당", ko: "알레르기가 있습니다.", th: "ผมมีอาการแพ้อาหารครับ", ro: "phom mee aa-gaan phae aa-haan khrab" },
  { c: "식당", ko: "고기를 먹지 않습니다.", th: "ผมไม่กินเนื้อครับ", ro: "phom mai gin nuea khrab" },

  { c: "쇼핑", ko: "이것을 사고 싶습니다.", th: "ผมอยากซื้ออันนี้ครับ", ro: "phom yaak sue an nee khrab" },
  { c: "쇼핑", ko: "다른 색이 있습니까?", th: "มีสีอื่นไหมครับ", ro: "mee see eun mai khrab" },
  { c: "쇼핑", ko: "다른 사이즈가 있습니까?", th: "มีไซซ์อื่นไหมครับ", ro: "mee size eun mai khrab" },
  { c: "쇼핑", ko: "입어봐도 됩니까?", th: "ลองใส่ได้ไหมครับ", ro: "long sai dai mai khrab" },
  { c: "쇼핑", ko: "카드로 결제할 수 있습니까?", th: "จ่ายบัตรได้ไหมครับ", ro: "jaai bat dai mai khrab" },
  { c: "쇼핑", ko: "현금으로 결제하겠습니다.", th: "ผมจะจ่ายเงินสดครับ", ro: "phom ja jaai ngoen sot khrab" },
  { c: "쇼핑", ko: "영수증 주세요.", th: "ขอใบเสร็จด้วยครับ", ro: "khor bai-set duai khrab" },
  { c: "쇼핑", ko: "봉투 주세요.", th: "ขอถุงด้วยครับ", ro: "khor thung duai khrab" },
  { c: "쇼핑", ko: "구경만 하고 있습니다.", th: "ผมแค่ดูเฉย ๆ ครับ", ro: "phom khae doo choei choei khrab" },
  { c: "쇼핑", ko: "이것은 마음에 듭니다.", th: "ผมชอบอันนี้ครับ", ro: "phom chob an nee khrab" },

  { c: "도움", ko: "도와주세요.", th: "ช่วยด้วยครับ", ro: "chuai duai khrab" },
  { c: "도움", ko: "길을 잃었습니다.", th: "ผมหลงทางครับ", ro: "phom long thaang khrab" },
  { c: "도움", ko: "휴대폰을 잃어버렸습니다.", th: "ผมทำโทรศัพท์หายครับ", ro: "phom tham toh-ra-sap haai khrab" },
  { c: "도움", ko: "지갑을 잃어버렸습니다.", th: "ผมทำกระเป๋าสตางค์หายครับ", ro: "phom tham gra-pao sa-taang haai khrab" },
  { c: "도움", ko: "아픕니다.", th: "ผมเจ็บครับ", ro: "phom jep khrab" },
  { c: "도움", ko: "병원에 가야 합니다.", th: "ผมต้องไปโรงพยาบาลครับ", ro: "phom dtong pai rohng pha-yaa-baan khrab" },
  { c: "도움", ko: "경찰을 불러 주세요.", th: "กรุณาเรียกตำรวจให้ครับ", ro: "ga-ru-naa riak dtam-ruat hai khrab" },
  { c: "도움", ko: "한국어를 할 수 있습니까?", th: "พูดภาษาเกาหลีได้ไหมครับ", ro: "phoot phaa-saa gao-lee dai mai khrab" },
  { c: "도움", ko: "영어를 할 수 있습니까?", th: "พูดภาษาอังกฤษได้ไหมครับ", ro: "phoot phaa-saa ang-grit dai mai khrab" },
  { c: "도움", ko: "사진을 찍어 주실 수 있습니까?", th: "ช่วยถ่ายรูปให้หน่อยได้ไหมครับ", ro: "chuai thaai roop hai noi dai mai khrab" },

  { c: "일상", ko: "오늘 날씨가 좋습니다.", th: "วันนี้อากาศดีครับ", ro: "wan nee aa-gaat dee khrab" },
  { c: "일상", ko: "오늘 춥습니다.", th: "วันนี้หนาวครับ", ro: "wan nee naao khrab" },
  { c: "일상", ko: "오늘 덥습니다.", th: "วันนี้ร้อนครับ", ro: "wan nee ron khrab" },
  { c: "일상", ko: "비가 옵니다.", th: "ฝนตกครับ", ro: "fon dtok khrab" },
  { c: "일상", ko: "피곤합니다.", th: "ผมเหนื่อยครับ", ro: "phom nueai khrab" },
  { c: "일상", ko: "배고픕니다.", th: "ผมหิวครับ", ro: "phom hiu khrab" },
  { c: "일상", ko: "목마릅니다.", th: "ผมหิวน้ำครับ", ro: "phom hiu naam khrab" },
  { c: "일상", ko: "괜찮으세요?", th: "คุณโอเคไหมครับ", ro: "khun oh-kay mai khrab" },
  { c: "일상", ko: "좋은 하루 되세요.", th: "ขอให้มีวันที่ดีครับ", ro: "khor hai mee wan thee dee khrab" },
  { c: "일상", ko: "다음에 연락하겠습니다.", th: "ผมจะติดต่ออีกครั้งครับ", ro: "phom ja dtit-dtor eek khrang khrab" },

  { c: "한국생활", ko: "주소를 알려 주세요.", th: "กรุณาบอกที่อยู่ครับ", ro: "ga-ru-naa bok thee-yuu khrab" },
  { c: "한국생활", ko: "전화번호를 알려 주세요.", th: "กรุณาบอกเบอร์โทรศัพท์ครับ", ro: "ga-ru-naa bok ber toh-ra-sap khrab" },
  { c: "한국생활", ko: "카카오톡을 사용합니까?", th: "ใช้คาเคาไหมครับ", ro: "chai Kakao mai khrab" },
  { c: "한국생활", ko: "지도 링크를 보내겠습니다.", th: "ผมจะส่งลิงก์แผนที่ให้ครับ", ro: "phom ja song link phaen-thee hai khrab" },
  { c: "한국생활", ko: "외국인등록증이 필요합니다.", th: "ต้องใช้บัตรคนต่างชาติครับ", ro: "dtong chai bat khon dtaang-chaat khrab" },
  { c: "한국생활", ko: "여권이 필요합니다.", th: "ต้องใช้หนังสือเดินทางครับ", ro: "dtong chai nang-sue doen-thaang khrab" },
  { c: "한국생활", ko: "예약이 필요합니다.", th: "ต้องจองก่อนครับ", ro: "dtong jong gon khrab" },
  { c: "한국생활", ko: "쓰레기는 정해진 날에 버립니다.", th: "ต้องทิ้งขยะตามวันที่กำหนดครับ", ro: "dtong thing kha-ya taam wan thee gam-not khrab" },
  { c: "한국생활", ko: "인터넷이 필요합니다.", th: "ต้องใช้อินเทอร์เน็ตครับ", ro: "dtong chai internet khrab" },
  { c: "한국생활", ko: "제가 확인해 보겠습니다.", th: "ผมจะตรวจสอบให้ครับ", ro: "phom ja dtruat-sop hai khrab" },

  // ===== 2026-06-04 확장분 (#101~200) =====
  { c: "이동", ko: "버스 정류장은 어디입니까?", th: "ป้ายรถเมล์อยู่ที่ไหนครับ", ro: "paai rot-mee yuu thee nai khrab" },
  { c: "이동", ko: "이 버스는 명동에 갑니까?", th: "รถเมล์คันนี้ไปเมียงดงไหมครับ", ro: "rot-mee khan nee pai Myeongdong mai khrab" },
  { c: "이동", ko: "표는 어디에서 삽니까?", th: "ซื้อตั๋วได้ที่ไหนครับ", ro: "sue tua dai thee nai khrab" },
  { c: "이동", ko: "얼마나 걸립니까?", th: "ใช้เวลานานเท่าไหร่ครับ", ro: "chai wee-laa naan thao-rai khrab" },
  { c: "이동", ko: "여기서 내릴게요.", th: "ผมจะลงที่นี่ครับ", ro: "phom ja long thee nee khrab" },
  { c: "이동", ko: "다음 역은 어디입니까?", th: "สถานีต่อไปคือที่ไหนครับ", ro: "sa-thaa-nee tor pai khue thee nai khrab" },
  { c: "이동", ko: "지도를 봐 주시겠어요?", th: "ช่วยดูแผนที่ให้หน่อยได้ไหมครับ", ro: "chuay duu phaen-thee hai noi dai mai khrab" },
  { c: "이동", ko: "공항까지 가 주세요.", th: "ไปสนามบินครับ", ro: "pai sa-naam-bin khrab" },
  { c: "이동", ko: "기차표를 예매하고 싶습니다.", th: "ผมอยากจองตั๋วรถไฟครับ", ro: "phom yaak jong tua rot-fai khrab" },
  { c: "이동", ko: "환승해야 합니까?", th: "ต้องเปลี่ยนสายไหมครับ", ro: "tong plian saai mai khrab" },

  { c: "식당", ko: "두 사람 자리 있습니까?", th: "มีที่นั่งสำหรับสองคนไหมครับ", ro: "mee thee nang sam-rap song khon mai khrab" },
  { c: "식당", ko: "예약했습니다.", th: "ผมจองไว้แล้วครับ", ro: "phom jong wai laeo khrab" },
  { c: "식당", ko: "추천 메뉴가 무엇입니까?", th: "เมนูแนะนำคืออะไรครับ", ro: "mee-nuu nae-nam khue a-rai khrab" },
  { c: "식당", ko: "이것은 무슨 요리입니까?", th: "อันนี้คืออาหารอะไรครับ", ro: "an nee khue aa-haan a-rai khrab" },
  { c: "식당", ko: "덜 맵게 해 주세요.", th: "ขอเผ็ดน้อยหน่อยครับ", ro: "khor phet noi noi khrab" },
  { c: "식당", ko: "고수는 빼 주세요.", th: "ไม่ใส่ผักชีครับ", ro: "mai sai phak-chee khrab" },
  { c: "식당", ko: "리필 됩니까?", th: "เติมได้ไหมครับ", ro: "term dai mai khrab" },
  { c: "식당", ko: "따로 계산해 주세요.", th: "คิดเงินแยกกันครับ", ro: "khit ngern yaek gan khrab" },
  { c: "식당", ko: "포장 됩니까?", th: "ใส่กล่องกลับบ้านได้ไหมครับ", ro: "sai glong glap baan dai mai khrab" },
  { c: "식당", ko: "아주 맛있었습니다.", th: "อร่อยมากครับ ขอบคุณครับ", ro: "a-roi maak khrab, khop khun khrab" },

  { c: "쇼핑", ko: "이것보다 싼 것 있습니까?", th: "มีถูกกว่านี้ไหมครับ", ro: "mee thuuk gwaa nee mai khrab" },
  { c: "쇼핑", ko: "새 것으로 주세요.", th: "ขอชิ้นใหม่ครับ", ro: "khor chin mai khrab" },
  { c: "쇼핑", ko: "교환할 수 있습니까?", th: "เปลี่ยนได้ไหมครับ", ro: "plian dai mai khrab" },
  { c: "쇼핑", ko: "환불해 주세요.", th: "ขอคืนเงินครับ", ro: "khor khuen ngern khrab" },
  { c: "쇼핑", ko: "선물 포장해 주세요.", th: "ช่วยห่อของขวัญให้หน่อยครับ", ro: "chuay hor khong-khwan hai noi khrab" },
  { c: "쇼핑", ko: "면세 됩니까?", th: "ขอคืนภาษีได้ไหมครับ", ro: "khor khuen phaa-see dai mai khrab" },
  { c: "쇼핑", ko: "영업시간이 어떻게 됩니까?", th: "เปิดกี่โมงถึงกี่โมงครับ", ro: "pert gee mohng thueng gee mohng khrab" },
  { c: "쇼핑", ko: "이것 두 개 주세요.", th: "ขออันนี้สองชิ้นครับ", ro: "khor an nee song chin khrab" },
  { c: "쇼핑", ko: "더 큰 것 있습니까?", th: "มีอันใหญ่กว่านี้ไหมครับ", ro: "mee an yai gwaa nee mai khrab" },
  { c: "쇼핑", ko: "인기 있는 것은 무엇입니까?", th: "อันไหนขายดีครับ", ro: "an nai khaai dee khrab", thFemale: "อันไหนขายดีคะ", roFemale: "an nai khaai dee kha" }, // 의문사가 문중이라 여성형 명시 (2026-06-04)

  { c: "병원", ko: "병원은 어디에 있습니까?", th: "โรงพยาบาลอยู่ที่ไหนครับ", ro: "rohng-pha-yaa-baan yuu thee nai khrab" },
  { c: "병원", ko: "약국은 어디에 있습니까?", th: "ร้านขายยาอยู่ที่ไหนครับ", ro: "raan khaai yaa yuu thee nai khrab" },
  { c: "병원", ko: "머리가 아픕니다.", th: "ผมปวดหัวครับ", ro: "phom puat hua khrab" },
  { c: "병원", ko: "배가 아픕니다.", th: "ผมปวดท้องครับ", ro: "phom puat thong khrab" },
  { c: "병원", ko: "열이 납니다.", th: "ผมมีไข้ครับ", ro: "phom mee khai khrab" },
  { c: "병원", ko: "감기에 걸렸습니다.", th: "ผมเป็นหวัดครับ", ro: "phom pen wat khrab" },
  { c: "병원", ko: "약 알레르기가 있습니다.", th: "ผมแพ้ยาครับ", ro: "phom phae yaa khrab" },
  { c: "병원", ko: "진통제 있습니까?", th: "มียาแก้ปวดไหมครับ", ro: "mee yaa gae puat mai khrab" },
  { c: "병원", ko: "하루에 몇 번 먹습니까?", th: "กินวันละกี่ครั้งครับ", ro: "gin wan la gee khrang khrab" },
  { c: "병원", ko: "보험이 있습니다.", th: "ผมมีประกันครับ", ro: "phom mee pra-gan khrab" },

  { c: "은행", ko: "계좌를 만들고 싶습니다.", th: "ผมอยากเปิดบัญชีครับ", ro: "phom yaak pert ban-chee khrab" },
  { c: "은행", ko: "환전하고 싶습니다.", th: "ผมอยากแลกเงินครับ", ro: "phom yaak laek ngern khrab" },
  { c: "은행", ko: "환율이 어떻게 됩니까?", th: "อัตราแลกเปลี่ยนเท่าไหร่ครับ", ro: "at-traa laek-plian thao-rai khrab" },
  { c: "은행", ko: "ATM은 어디에 있습니까?", th: "ตู้เอทีเอ็มอยู่ที่ไหนครับ", ro: "tuu ee-thee-em yuu thee nai khrab" },
  { c: "은행", ko: "송금하고 싶습니다.", th: "ผมอยากโอนเงินครับ", ro: "phom yaak ohn ngern khrab" },
  { c: "은행", ko: "외국인등록증이 필요합니까?", th: "ต้องใช้บัตรคนต่างชาติไหมครับ", ro: "tong chai bat khon taang-chaat mai khrab" },
  { c: "은행", ko: "이 서류 작성을 도와주세요.", th: "ช่วยกรอกเอกสารให้หน่อยครับ", ro: "chuay grok ek-ga-saan hai noi khrab" },
  { c: "은행", ko: "비자를 연장하고 싶습니다.", th: "ผมอยากต่อวีซ่าครับ", ro: "phom yaak tor wee-saa khrab" },
  { c: "은행", ko: "여기에 서명하면 됩니까?", th: "เซ็นชื่อตรงนี้ใช่ไหมครับ", ro: "sen chue trong nee chai mai khrab" },
  { c: "은행", ko: "수수료가 있습니까?", th: "มีค่าธรรมเนียมไหมครับ", ro: "mee khaa tham-niam mai khrab" },

  { c: "숙소", ko: "빈 방 있습니까?", th: "มีห้องว่างไหมครับ", ro: "mee hong waang mai khrab" },
  { c: "숙소", ko: "하룻밤에 얼마입니까?", th: "คืนละเท่าไหร่ครับ", ro: "khuen la thao-rai khrab" },
  { c: "숙소", ko: "체크인하고 싶습니다.", th: "ผมขอเช็คอินครับ", ro: "phom khor chek-in khrab" },
  { c: "숙소", ko: "체크아웃은 몇 시입니까?", th: "เช็คเอาท์กี่โมงครับ", ro: "chek-ao gee mohng khrab" },
  { c: "숙소", ko: "와이파이 비밀번호가 무엇입니까?", th: "รหัสไวไฟคืออะไรครับ", ro: "ra-hat wai-fai khue a-rai khrab" },
  { c: "숙소", ko: "짐을 맡길 수 있습니까?", th: "ฝากกระเป๋าได้ไหมครับ", ro: "faak gra-pao dai mai khrab" },
  { c: "숙소", ko: "방을 바꾸고 싶습니다.", th: "ผมอยากเปลี่ยนห้องครับ", ro: "phom yaak plian hong khrab" },
  { c: "숙소", ko: "에어컨이 고장 났습니다.", th: "แอร์เสียครับ", ro: "ae sia khrab" },
  { c: "숙소", ko: "수건을 더 주세요.", th: "ขอผ้าเช็ดตัวเพิ่มครับ", ro: "khor phaa-chet-tua perm khrab" },
  { c: "숙소", ko: "하루 더 묵고 싶습니다.", th: "ผมอยากพักต่ออีกคืนครับ", ro: "phom yaak phak tor eek khuen khrab" },

  { c: "부동산", ko: "방을 구하고 있습니다.", th: "ผมกำลังหาห้องเช่าครับ", ro: "phom gam-lang haa hong chao khrab" },
  { c: "부동산", ko: "월세는 얼마입니까?", th: "ค่าเช่าเดือนละเท่าไหร่ครับ", ro: "khaa chao duean la thao-rai khrab" },
  { c: "부동산", ko: "보증금은 얼마입니까?", th: "เงินมัดจำเท่าไหร่ครับ", ro: "ngern mat-jam thao-rai khrab" },
  { c: "부동산", ko: "관리비가 포함되어 있습니까?", th: "รวมค่าส่วนกลางไหมครับ", ro: "ruam khaa suan-glaang mai khrab" },
  { c: "부동산", ko: "방을 보고 싶습니다.", th: "ผมขอดูห้องหน่อยครับ", ro: "phom khor duu hong noi khrab" },
  { c: "부동산", ko: "언제 입주할 수 있습니까?", th: "เข้าอยู่ได้เมื่อไหร่ครับ", ro: "khao yuu dai muea-rai khrab" },
  { c: "부동산", ko: "계약 기간은 얼마나 됩니까?", th: "สัญญากี่ปีครับ", ro: "san-yaa gee pee khrab" },
  { c: "부동산", ko: "가구가 포함되어 있습니까?", th: "มีเฟอร์นิเจอร์ไหมครับ", ro: "mee fer-ni-jer mai khrab" },
  { c: "부동산", ko: "지하철역에서 가깝습니까?", th: "ใกล้สถานีรถไฟฟ้าไหมครับ", ro: "glai sa-thaa-nee rot-fai-faa mai khrab" },
  { c: "부동산", ko: "계약서를 천천히 읽고 싶습니다.", th: "ผมขออ่านสัญญาช้า ๆ ครับ", ro: "phom khor aan san-yaa chaa chaa khrab" },

  { c: "직장", ko: "잘 부탁드립니다.", th: "ฝากเนื้อฝากตัวด้วยครับ", ro: "faak nuea faak tua duay khrab" },
  { c: "직장", ko: "회의는 몇 시입니까?", th: "ประชุมกี่โมงครับ", ro: "pra-chum gee mohng khrab" },
  { c: "직장", ko: "잠시 쉬어도 됩니까?", th: "ขอพักสักครู่ได้ไหมครับ", ro: "khor phak sak khruu dai mai khrab" },
  { c: "직장", ko: "이것을 도와주시겠어요?", th: "ช่วยผมหน่อยได้ไหมครับ", ro: "chuay phom noi dai mai khrab" },
  { c: "직장", ko: "언제까지 끝내야 합니까?", th: "ต้องเสร็จเมื่อไหร่ครับ", ro: "tong set muea-rai khrab" },
  { c: "직장", ko: "다시 설명해 주시겠어요?", th: "ช่วยอธิบายอีกครั้งได้ไหมครับ", ro: "chuay a-thi-baai eek khrang dai mai khrab" },
  { c: "직장", ko: "알겠습니다. 바로 하겠습니다.", th: "เข้าใจแล้วครับ จะทำเลยครับ", ro: "khao jai laeo khrab, ja tham loei khrab" },
  { c: "직장", ko: "오늘 야근합니까?", th: "วันนี้ทำโอทีไหมครับ", ro: "wan nee tham oh-thee mai khrab" },
  { c: "직장", ko: "월급날은 언제입니까?", th: "เงินเดือนออกวันไหนครับ", ro: "ngern duean ork wan nai khrab" },
  { c: "직장", ko: "휴가를 내고 싶습니다.", th: "ผมอยากลาหยุดครับ", ro: "phom yaak laa yut khrab" },

  { c: "도움", ko: "응급 상황입니다.", th: "เป็นเหตุฉุกเฉินครับ", ro: "pen het chuk-chern khrab" },
  { c: "도움", ko: "구급차를 불러 주세요.", th: "ช่วยเรียกรถพยาบาลให้หน่อยครับ", ro: "chuay riak rot pha-yaa-baan hai noi khrab" },
  { c: "도움", ko: "불이 났습니다.", th: "ไฟไหม้ครับ", ro: "fai mai khrab" },
  { c: "도움", ko: "여권을 잃어버렸습니다.", th: "ผมทำพาสปอร์ตหายครับ", ro: "phom tham phaat-sa-port haai khrab" },
  { c: "도움", ko: "도둑맞았습니다.", th: "ผมโดนขโมยของครับ", ro: "phom dohn kha-moy khong khrab" },
  { c: "도움", ko: "대사관에 연락하고 싶습니다.", th: "ผมอยากติดต่อสถานทูตครับ", ro: "phom yaak tit-tor sa-thaan-thuut khrab" },
  { c: "도움", ko: "한국어 통역이 필요합니다.", th: "ผมต้องการล่ามภาษาเกาหลีครับ", ro: "phom tong-gaan laam phaa-saa gao-lee khrab" },
  { c: "도움", ko: "여기가 안전합니까?", th: "ที่นี่ปลอดภัยไหมครับ", ro: "thee nee plort-phai mai khrab" },
  { c: "도움", ko: "경찰서는 어디입니까?", th: "สถานีตำรวจอยู่ที่ไหนครับ", ro: "sa-thaa-nee tam-ruat yuu thee nai khrab" },
  { c: "도움", ko: "분실물 센터는 어디입니까?", th: "ศูนย์ของหายอยู่ที่ไหนครับ", ro: "suun khong haai yuu thee nai khrab" },

  { c: "일상", ko: "주말에 무엇을 하세요?", th: "วันหยุดสุดสัปดาห์ทำอะไรครับ", ro: "wan yut sut sap-daa tham a-rai khrab" },
  { c: "일상", ko: "취미가 무엇입니까?", th: "งานอดิเรกคืออะไรครับ", ro: "ngaan a-di-rek khue a-rai khrab" },
  { c: "일상", ko: "한국 음식을 좋아합니까?", th: "ชอบอาหารเกาหลีไหมครับ", ro: "chop aa-haan gao-lee mai khrab" },
  { c: "일상", ko: "가장 좋아하는 음식은 무엇입니까?", th: "อาหารที่ชอบที่สุดคืออะไรครับ", ro: "aa-haan thee chop thee-sut khue a-rai khrab" },
  { c: "일상", ko: "한국은 처음입니까?", th: "มาเกาหลีครั้งแรกหรือครับ", ro: "maa gao-lee khrang raek rue khrab" },
  { c: "일상", ko: "사진 찍어 드릴까요?", th: "ให้ผมถ่ายรูปให้ไหมครับ", ro: "hai phom thaai ruup hai mai khrab" },
  { c: "일상", ko: "연락처를 교환합시다.", th: "แลกเบอร์กันเถอะครับ", ro: "laek ber gan thuh khrab" },
  { c: "일상", ko: "다음에 같이 식사해요.", th: "ไว้ไปกินข้าวด้วยกันนะครับ", ro: "wai pai gin khaao duay gan na khrab" },
  { c: "일상", ko: "한국 생활은 어떻습니까?", th: "ชีวิตที่เกาหลีเป็นยังไงบ้างครับ", ro: "chee-wit thee gao-lee pen yang-ngai baang khrab" },
  { c: "일상", ko: "만나서 즐거웠습니다.", th: "ยินดีที่ได้เจอกันครับ", ro: "yin-dee thee dai jer gan khrab" }
];

function makeFemaleThai(text) {
  let value = text
    .replaceAll("ผม", "ฉัน")
    .replaceAll("ครับ", "ค่ะ");

  // const questionPatterns = ["ไหมค่ะ", "อะไรค่ะ", "ที่ไหนค่ะ", "เท่าไหร่ค่ะ", "กี่โมงค่ะ"]; // 구 코드: #101~200 확장 의문문 미포함 (2026-06-04 보강)
  // 의문문 끝은 ค่ะ가 아니라 คะ. "ไหนค่ะ"는 ที่ไหน/อันไหน/วันไหน 모두 포괄
  const questionPatterns = ["ไหมค่ะ", "อะไรค่ะ", "ไหนค่ะ", "เท่าไหร่ค่ะ", "กี่โมงค่ะ", "เมื่อไหร่ค่ะ", "กี่ครั้งค่ะ", "กี่ปีค่ะ", "หรือค่ะ", "บ้างค่ะ"];
  questionPatterns.forEach((pattern) => {
    value = value.replaceAll(pattern, pattern.replace("ค่ะ", "คะ"));
  });

  return value;
}

function makeFemaleRoman(text) {
  return text
    .replaceAll("phom", "chan")
    .replaceAll("khrab", "kha");
}

window.WIIINFO_MAKE_FEMALE_THAI = makeFemaleThai;
window.WIIINFO_MAKE_FEMALE_ROMAN = makeFemaleRoman;

window.THAI_PHRASES = window.THAI_PHRASES.map((phrase, index) => ({
  ...phrase,
  n: phrase.n || index + 1,
  thMale: phrase.th,
  roMale: phrase.ro,
  thFemale: phrase.thFemale || makeFemaleThai(phrase.th),
  roFemale: phrase.roFemale || makeFemaleRoman(phrase.ro)
}));

window.THAI_LETTERS = [
  { type: "자음", char: "ก", name: "กอ ไก่", sound: "gaw gai · 한국어 ㄱ에 가까운 소리", example: "ไก่(gai) 닭" },
  { type: "자음", char: "ข", name: "ขอ ไข่", sound: "khor khai · 숨이 섞인 ㅋ 계열", example: "ไข่(khai) 달걀" },
  { type: "자음", char: "ค", name: "คอ ควาย", sound: "khor khwaai · ㅋ 계열", example: "ควาย(khwaai) 물소" },
  { type: "자음", char: "ง", name: "งอ งู", sound: "ngor nguu · 받침 ㅇ/ng 소리", example: "งู(nguu) 뱀" },
  { type: "자음", char: "จ", name: "จอ จาน", sound: "jor jaan · ㅈ에 가까운 소리", example: "จาน(jaan) 접시" },
  { type: "자음", char: "ช", name: "ชอ ช้าง", sound: "chor chaang · ㅊ 계열", example: "ช้าง(chaang) 코끼리" },
  { type: "자음", char: "ซ", name: "ซอ โซ่", sound: "sor soh · ㅅ/s 소리", example: "โซ่(soh) 사슬" },
  { type: "자음", char: "ด", name: "ดอ เด็ก", sound: "dor dek · ㄷ에 가까운 소리", example: "เด็ก(dek) 아이" },
  { type: "자음", char: "ต", name: "ตอ เต่า", sound: "dtor dtao · 된 ㄸ/ㄷ 계열", example: "เต่า(dtao) 거북이" },
  { type: "자음", char: "ท", name: "ทอ ทหาร", sound: "thor tha-haan · ㅌ 계열", example: "ทหาร(tha-haan) 군인" },
  { type: "자음", char: "น", name: "นอ หนู", sound: "nor nuu · ㄴ 소리", example: "หนู(nuu) 쥐" },
  { type: "자음", char: "บ", name: "บอ ใบไม้", sound: "bor bai-mai · ㅂ에 가까운 소리", example: "ใบไม้(bai-mai) 잎" },
  { type: "자음", char: "ป", name: "ปอ ปลา", sound: "bpor bplaa · 된 ㅃ/ㅂ 계열", example: "ปลา(bplaa) 물고기" },
  { type: "자음", char: "ผ", name: "ผอ ผึ้ง", sound: "phor pheung · ㅍ 계열", example: "ผึ้ง(pheung) 벌" },
  { type: "자음", char: "พ", name: "พอ พาน", sound: "phor phaan · ㅍ 계열", example: "พาน(phaan) 쟁반" },
  { type: "자음", char: "ฟ", name: "ฟอ ฟัน", sound: "for fan · f 소리", example: "ฟัน(fan) 이빨" },
  { type: "자음", char: "ม", name: "มอ ม้า", sound: "mor maa · ㅁ 소리", example: "ม้า(maa) 말" },
  { type: "자음", char: "ย", name: "ยอ ยักษ์", sound: "yor yak · y/이 계열", example: "ยักษ์(yak) 거인" },
  { type: "자음", char: "ร", name: "รอ เรือ", sound: "ror ruea · r 소리", example: "เรือ(ruea) 배" },
  { type: "자음", char: "ล", name: "ลอ ลิง", sound: "lor ling · ㄹ/l 소리", example: "ลิง(ling) 원숭이" },
  { type: "자음", char: "ว", name: "วอ แหวน", sound: "wor waen · w 소리", example: "แหวน(waen) 반지" },
  { type: "자음", char: "ส", name: "สอ เสือ", sound: "sor suea · ㅅ/s 소리", example: "เสือ(suea) 호랑이" },
  { type: "자음", char: "ห", name: "หอ หีบ", sound: "hor heep · h 소리", example: "หีบ(heep) 상자" },
  { type: "자음", char: "อ", name: "ออ อ่าง", sound: "or aang · 모음 받침/무음 자음 역할", example: "อ่าง(aang) 대야" },

  { type: "모음", char: "ะ", name: "สระ อะ", sound: "a · 짧은 아", example: "จะ(ja) ~할 것이다" },
  { type: "모음", char: "า", name: "สระ อา", sound: "aa · 긴 아", example: "มา(maa) 오다" },
  { type: "모음", char: "ิ", name: "สระ อิ", sound: "i · 짧은 이", example: "กิน(gin) 먹다" },
  { type: "모음", char: "ี", name: "สระ อี", sound: "ii · 긴 이", example: "ดี(dee) 좋다" },
  { type: "모음", char: "ึ", name: "สระ อึ", sound: "ue · 짧은 으 계열", example: "หนึ่ง(neung) 하나" },
  { type: "모음", char: "ื", name: "สระ อือ", sound: "ueu · 긴 으 계열", example: "ชื่อ(chue) 이름" },
  { type: "모음", char: "ุ", name: "สระ อุ", sound: "u · 짧은 우", example: "คุณ(khun) 당신" },
  { type: "모음", char: "ู", name: "สระ อู", sound: "uu · 긴 우", example: "ดู(duu) 보다" },
  { type: "모음", char: "เ", name: "สระ เอ", sound: "ee/eh · 에 계열", example: "เกาหลี(gao-lee) 한국" },
  { type: "모음", char: "แ", name: "สระ แอ", sound: "ae · 애 계열", example: "แม่(mae) 엄마" },
  { type: "모음", char: "โ", name: "สระ โอ", sound: "oh · 오 계열", example: "โต๊ะ(dto) 책상" },
  { type: "모음", char: "ใ", name: "สระ ใอ", sound: "ai · 아이", example: "ใช่(chai) 맞다" },
  { type: "모음", char: "ไ", name: "สระ ไอ", sound: "ai · 아이", example: "ไทย(thai) 태국" },
  { type: "모음", char: "ำ", name: "สระ อำ", sound: "am · 암", example: "น้ำ(naam) 물" }
];

window.KOREAN_LETTERS = [
  { type: "พยัญชนะเกาหลี", char: "ㄱ", name: "기역", sound: "g/k · เสียงใกล้ ก/ค", example: "가(ga)" },
  { type: "พยัญชนะเกาหลี", char: "ㄴ", name: "니은", sound: "n · เสียงใกล้ น", example: "나(na)" },
  { type: "พยัญชนะเกาหลี", char: "ㄷ", name: "디귿", sound: "d/t · เสียงใกล้ ด/ท", example: "다(da)" },
  { type: "พยัญชนะเกาหลี", char: "ㄹ", name: "리을", sound: "r/l · เสียงอยู่ระหว่าง ร และ ล", example: "라(ra)" },
  { type: "พยัญชนะเกาหลี", char: "ㅁ", name: "미음", sound: "m · เสียงใกล้ ม", example: "마(ma)" },
  { type: "พยัญชนะเกาหลี", char: "ㅂ", name: "비읍", sound: "b/p · เสียงใกล้ บ/ป", example: "바(ba)" },
  { type: "พยัญชนะเกาหลี", char: "ㅅ", name: "시옷", sound: "s · เสียงใกล้ ซ/ส", example: "사(sa)" },
  { type: "พยัญชนะเกาหลี", char: "ㅇ", name: "이응", sound: "ng หรือไม่มีเสียงเมื่อต้นพยางค์", example: "아(a), 강(gang)" },
  { type: "พยัญชนะเกาหลี", char: "ㅈ", name: "지읒", sound: "j · เสียงใกล้ จ", example: "자(ja)" },
  { type: "พยัญชนะเกาหลี", char: "ㅊ", name: "치읓", sound: "ch · เสียงใกล้ ช", example: "차(cha)" },
  { type: "พยัญชนะเกาหลี", char: "ㅋ", name: "키읔", sound: "k · เสียงใกล้ ค/ข", example: "카(ka)" },
  { type: "พยัญชนะเกาหลี", char: "ㅌ", name: "티읕", sound: "t · เสียงใกล้ ท", example: "타(ta)" },
  { type: "พยัญชนะเกาหลี", char: "ㅍ", name: "피읖", sound: "p · เสียงใกล้ พ/ผ", example: "파(pa)" },
  { type: "พยัญชนะเกาหลี", char: "ㅎ", name: "히읗", sound: "h · เสียงใกล้ ห", example: "하(ha)" },
  { type: "สระเกาหลี", char: "ㅏ", name: "아", sound: "a · เสียง อา", example: "아(a)" },
  { type: "สระเกาหลี", char: "ㅑ", name: "야", sound: "ya · เสียง ยา", example: "야(ya)" },
  { type: "สระเกาหลี", char: "ㅓ", name: "어", sound: "eo · เสียง ออ/เออ", example: "어(eo)" },
  { type: "สระเกาหลี", char: "ㅕ", name: "여", sound: "yeo · เสียง ยอ/เยอ", example: "여(yeo)" },
  { type: "สระเกาหลี", char: "ㅗ", name: "오", sound: "o · เสียง โอ", example: "오(o)" },
  { type: "สระเกาหลี", char: "ㅛ", name: "요", sound: "yo · เสียง โย", example: "요(yo)" },
  { type: "สระเกาหลี", char: "ㅜ", name: "우", sound: "u · เสียง อู", example: "우(u)" },
  { type: "สระเกาหลี", char: "ㅠ", name: "유", sound: "yu · เสียง ยู", example: "유(yu)" },
  { type: "สระเกาหลี", char: "ㅡ", name: "으", sound: "eu · เสียง อือ", example: "으(eu)" },
  { type: "สระเกาหลี", char: "ㅣ", name: "이", sound: "i · เสียง อี", example: "이(i)" }
];
