window.THAI_PHRASES = [
  { c: "인사", ko: "안녕하세요.", th: "สวัสดีครับ", ro: "sa-wat-dee khrab" },
  { c: "인사", ko: "안녕하세요. 만나서 반갑습니다.", th: "สวัสดีครับ ยินดีที่ได้รู้จักครับ", ro: "sa-wat-dee khrab, yin-dee thee dai roo-jak khrab" },
  { c: "인사", ko: "감사합니다.", th: "ขอบคุณครับ", ro: "khop khun khrab" },
  { c: "인사", ko: "정말 감사합니다.", th: "ขอบคุณมากครับ", ro: "khop khun maak khrab" },
  { c: "인사", ko: "죄송합니다.", th: "ขอโทษครับ", ro: "khor thot khrab" },
  { c: "인사", ko: "괜찮습니다.", th: "ไม่เป็นไรครับ", ro: "mai pen rai khrab" },
  { c: "인사", ko: "잘 지내세요?", th: "สบายดีไหมครับ", ro: "sa-baai dee mai khrab" },
  { c: "인사", ko: "잘 지냅니다.", th: "สบายดีครับ", ro: "sa-baai dee khrab" },
  { c: "인사", ko: "또 만나요.", th: "แล้วพบกันใหม่ครับ", ro: "laeo phop gan mai khrab" },
  { c: "인사", ko: "안녕히 가세요.", th: "ลาก่อนครับ", ro: "laa gon khrab" },

  { c: "자기소개", ko: "저는 한국 사람입니다.", th: "ผมเป็นคนเกาหลี", ro: "phom pen khon gao-lee" },
  { c: "자기소개", ko: "저는 한국에서 왔습니다.", th: "ผมมาจากเกาหลี", ro: "phom maa jaak gao-lee" },
  { c: "자기소개", ko: "제 이름은 ___입니다.", th: "ผมชื่อ ___", ro: "phom chue ___" },
  { c: "자기소개", ko: "당신의 이름은 무엇입니까?", th: "คุณชื่ออะไรครับ", ro: "khun chue a-rai khrab" },
  { c: "자기소개", ko: "저는 태국어를 배우고 있습니다.", th: "ผมกำลังเรียนภาษาไทย", ro: "phom gam-lang rian phaa-saa thai" },
  { c: "자기소개", ko: "태국어를 조금 할 수 있습니다.", th: "ผมพูดภาษาไทยได้นิดหน่อย", ro: "phom phoot phaa-saa thai dai nit noi" },
  { c: "자기소개", ko: "저는 영어를 조금 할 수 있습니다.", th: "ผมพูดภาษาอังกฤษได้นิดหน่อย", ro: "phom phoot phaa-saa ang-grit dai nit noi" },
  { c: "자기소개", ko: "저는 이해했습니다.", th: "ผมเข้าใจแล้วครับ", ro: "phom khao jai laeo khrab" },
  { c: "자기소개", ko: "저는 이해하지 못했습니다.", th: "ผมไม่เข้าใจครับ", ro: "phom mai khao jai khrab" },
  { c: "자기소개", ko: "천천히 말씀해 주세요.", th: "กรุณาพูดช้า ๆ ครับ", ro: "ga-ru-naa phoot chaa chaa khrab" },

  { c: "기초응답", ko: "네.", th: "ใช่ครับ", ro: "chai khrab" },
  { c: "기초응답", ko: "아니요.", th: "ไม่ใช่ครับ", ro: "mai chai khrab" },
  { c: "기초응답", ko: "맞습니다.", th: "ถูกต้องครับ", ro: "thook tong khrab" },
  { c: "기초응답", ko: "아닙니다.", th: "ไม่ถูกครับ", ro: "mai thook khrab" },
  { c: "기초응답", ko: "좋습니다.", th: "ดีครับ", ro: "dee khrab" },
  { c: "기초응답", ko: "좋지 않습니다.", th: "ไม่ดีครับ", ro: "mai dee khrab" },
  { c: "기초응답", ko: "괜찮아요?", th: "โอเคไหมครับ", ro: "oh-kay mai khrab" },
  { c: "기초응답", ko: "괜찮아요.", th: "โอเคครับ", ro: "oh-kay khrab" },
  { c: "기초응답", ko: "문제 없습니다.", th: "ไม่มีปัญหาครับ", ro: "mai mee pan-haa khrab" },
  { c: "기초응답", ko: "다시 말해 주세요.", th: "กรุณาพูดอีกครั้งครับ", ro: "ga-ru-naa phoot eek khrang khrab" },

  { c: "숫자/시간", ko: "이것은 얼마입니까?", th: "อันนี้ราคาเท่าไหร่ครับ", ro: "an nee raa-khaa thao-rai khrab" },
  { c: "숫자/시간", ko: "너무 비쌉니다.", th: "แพงเกินไปครับ", ro: "phaeng gern pai khrab" },
  { c: "숫자/시간", ko: "조금 깎아 주세요.", th: "ลดราคาให้หน่อยครับ", ro: "lot raa-khaa hai noi khrab" },
  { c: "숫자/시간", ko: "몇 시입니까?", th: "กี่โมงครับ", ro: "gee mohng khrab" },
  { c: "숫자/시간", ko: "오늘입니다.", th: "วันนี้ครับ", ro: "wan nee khrab" },
  { c: "숫자/시간", ko: "내일입니다.", th: "พรุ่งนี้ครับ", ro: "phrung nee khrab" },
  { c: "숫자/시간", ko: "어제입니다.", th: "เมื่อวานครับ", ro: "muea waan khrab" },
  { c: "숫자/시간", ko: "지금 가겠습니다.", th: "ผมจะไปตอนนี้ครับ", ro: "phom ja pai ton nee khrab" },
  { c: "숫자/시간", ko: "잠시만 기다려 주세요.", th: "กรุณารอสักครู่ครับ", ro: "ga-ru-naa ror sak khroo khrab" },
  { c: "숫자/시간", ko: "10분 정도 걸립니다.", th: "ใช้เวลาประมาณสิบนาทีครับ", ro: "chai way-laa pra-maan sip naa-thee khrab" },

  { c: "이동", ko: "여기는 어디입니까?", th: "ที่นี่ที่ไหนครับ", ro: "thee nee thee nai khrab" },
  { c: "이동", ko: "화장실은 어디입니까?", th: "ห้องน้ำอยู่ที่ไหนครับ", ro: "hong naam yuu thee nai khrab" },
  { c: "이동", ko: "지하철역은 어디입니까?", th: "สถานีรถไฟใต้ดินอยู่ที่ไหนครับ", ro: "sa-thaa-nee rot-fai dtai-din yuu thee nai khrab" },
  { c: "이동", ko: "이쪽으로 오세요.", th: "เชิญทางนี้ครับ", ro: "choen thaang nee khrab" },
  { c: "이동", ko: "저쪽으로 가세요.", th: "ไปทางนั้นครับ", ro: "pai thaang nan khrab" },
  { c: "이동", ko: "오른쪽으로 가세요.", th: "ไปทางขวาครับ", ro: "pai thaang khwaa khrab" },
  { c: "이동", ko: "왼쪽으로 가세요.", th: "ไปทางซ้ายครับ", ro: "pai thaang saai khrab" },
  { c: "이동", ko: "곧장 가세요.", th: "ตรงไปครับ", ro: "dtrong pai khrab" },
  { c: "이동", ko: "택시를 타고 싶습니다.", th: "ผมอยากนั่งแท็กซี่ครับ", ro: "phom yaak nang taxi khrab" },
  { c: "이동", ko: "여기서 내려 주세요.", th: "จอดตรงนี้ครับ", ro: "jot dtrong nee khrab" },

  { c: "식당", ko: "메뉴 주세요.", th: "ขอเมนูหน่อยครับ", ro: "khor menu noi khrab" },
  { c: "식당", ko: "이것을 주세요.", th: "ขออันนี้ครับ", ro: "khor an nee khrab" },
  { c: "식당", ko: "물을 주세요.", th: "ขอน้ำหน่อยครับ", ro: "khor naam noi khrab" },
  { c: "식당", ko: "맵지 않게 해 주세요.", th: "ขอไม่เผ็ดครับ", ro: "khor mai phet khrab" },
  { c: "식당", ko: "조금 맵게 해 주세요.", th: "ขอเผ็ดนิดหน่อยครับ", ro: "khor phet nit noi khrab" },
  { c: "식당", ko: "맛있습니다.", th: "อร่อยครับ", ro: "a-roi khrab" },
  { c: "식당", ko: "계산해 주세요.", th: "เช็กบิลด้วยครับ", ro: "check bin duai khrab" },
  { c: "식당", ko: "포장해 주세요.", th: "ใส่ถุงกลับบ้านครับ", ro: "sai thung glap baan khrab" },
  { c: "식당", ko: "알레르기가 있습니다.", th: "ผมมีอาการแพ้อาหารครับ", ro: "phom mee aa-gaan phae aa-haan khrab" },
  { c: "식당", ko: "고기를 먹지 않습니다.", th: "ผมไม่กินเนื้อครับ", ro: "phom mai gin nuea khrab" },

  { c: "쇼핑", ko: "이것을 사고 싶습니다.", th: "ผมอยากซื้ออันนี้ครับ", ro: "phom yaak sue an nee khrab" },
  { c: "쇼핑", ko: "다른 색이 있습니까?", th: "มีสีอื่นไหมครับ", ro: "mee see eun mai khrab" },
  { c: "쇼핑", ko: "다른 사이즈가 있습니까?", th: "มีไซซ์อื่นไหมครับ", ro: "mee size eun mai khrab" },
  { c: "쇼핑", ko: "입어봐도 됩니까?", th: "ลองใส่ได้ไหมครับ", ro: "long sai dai mai khrab" },
  { c: "쇼핑", ko: "카드로 결제할 수 있습니까?", th: "จ่ายบัตรได้ไหมครับ", ro: "jaai bat dai mai khrab" },
  { c: "쇼핑", ko: "현금으로 결제하겠습니다.", th: "ผมจะจ่ายเงินสดครับ", ro: "phom ja jaai ngoen sot khrab" },
  { c: "쇼핑", ko: "영수증 주세요.", th: "ขอใบเสร็จด้วยครับ", ro: "khor bai-set duai khrab" },
  { c: "쇼핑", ko: "봉투 주세요.", th: "ขอถุงด้วยครับ", ro: "khor thung duai khrab" },
  { c: "쇼핑", ko: "구경만 하고 있습니다.", th: "ผมแค่ดูเฉย ๆ ครับ", ro: "phom khae doo choei choei khrab" },
  { c: "쇼핑", ko: "이것은 마음에 듭니다.", th: "ผมชอบอันนี้ครับ", ro: "phom chob an nee khrab" },

  { c: "도움", ko: "도와주세요.", th: "ช่วยด้วยครับ", ro: "chuai duai khrab" },
  { c: "도움", ko: "길을 잃었습니다.", th: "ผมหลงทางครับ", ro: "phom long thaang khrab" },
  { c: "도움", ko: "휴대폰을 잃어버렸습니다.", th: "ผมทำโทรศัพท์หายครับ", ro: "phom tham toh-ra-sap haai khrab" },
  { c: "도움", ko: "지갑을 잃어버렸습니다.", th: "ผมทำกระเป๋าสตางค์หายครับ", ro: "phom tham gra-pao sa-taang haai khrab" },
  { c: "도움", ko: "아픕니다.", th: "ผมเจ็บครับ", ro: "phom jep khrab" },
  { c: "도움", ko: "병원에 가야 합니다.", th: "ผมต้องไปโรงพยาบาลครับ", ro: "phom dtong pai rohng pha-yaa-baan khrab" },
  { c: "도움", ko: "경찰을 불러 주세요.", th: "กรุณาเรียกตำรวจให้ครับ", ro: "ga-ru-naa riak dtam-ruat hai khrab" },
  { c: "도움", ko: "한국어를 할 수 있습니까?", th: "พูดภาษาเกาหลีได้ไหมครับ", ro: "phoot phaa-saa gao-lee dai mai khrab" },
  { c: "도움", ko: "영어를 할 수 있습니까?", th: "พูดภาษาอังกฤษได้ไหมครับ", ro: "phoot phaa-saa ang-grit dai mai khrab" },
  { c: "도움", ko: "사진을 찍어 주실 수 있습니까?", th: "ช่วยถ่ายรูปให้หน่อยได้ไหมครับ", ro: "chuai thaai roop hai noi dai mai khrab" },

  { c: "일상", ko: "오늘 날씨가 좋습니다.", th: "วันนี้อากาศดีครับ", ro: "wan nee aa-gaat dee khrab" },
  { c: "일상", ko: "오늘 춥습니다.", th: "วันนี้หนาวครับ", ro: "wan nee naao khrab" },
  { c: "일상", ko: "오늘 덥습니다.", th: "วันนี้ร้อนครับ", ro: "wan nee ron khrab" },
  { c: "일상", ko: "비가 옵니다.", th: "ฝนตกครับ", ro: "fon dtok khrab" },
  { c: "일상", ko: "피곤합니다.", th: "ผมเหนื่อยครับ", ro: "phom nueai khrab" },
  { c: "일상", ko: "배고픕니다.", th: "ผมหิวครับ", ro: "phom hiu khrab" },
  { c: "일상", ko: "목마릅니다.", th: "ผมหิวน้ำครับ", ro: "phom hiu naam khrab" },
  { c: "일상", ko: "괜찮으세요?", th: "คุณโอเคไหมครับ", ro: "khun oh-kay mai khrab" },
  { c: "일상", ko: "좋은 하루 되세요.", th: "ขอให้มีวันที่ดีครับ", ro: "khor hai mee wan thee dee khrab" },
  { c: "일상", ko: "다음에 연락하겠습니다.", th: "ผมจะติดต่ออีกครั้งครับ", ro: "phom ja dtit-dtor eek khrang khrab" },

  { c: "한국생활", ko: "주소를 알려 주세요.", th: "กรุณาบอกที่อยู่ครับ", ro: "ga-ru-naa bok thee-yuu khrab" },
  { c: "한국생활", ko: "전화번호를 알려 주세요.", th: "กรุณาบอกเบอร์โทรศัพท์ครับ", ro: "ga-ru-naa bok ber toh-ra-sap khrab" },
  { c: "한국생활", ko: "카카오톡을 사용합니까?", th: "ใช้คาเคาไหมครับ", ro: "chai Kakao mai khrab" },
  { c: "한국생활", ko: "지도 링크를 보내겠습니다.", th: "ผมจะส่งลิงก์แผนที่ให้ครับ", ro: "phom ja song link phaen-thee hai khrab" },
  { c: "한국생활", ko: "외국인등록증이 필요합니다.", th: "ต้องใช้บัตรคนต่างชาติครับ", ro: "dtong chai bat khon dtaang-chaat khrab" },
  { c: "한국생활", ko: "여권이 필요합니다.", th: "ต้องใช้หนังสือเดินทางครับ", ro: "dtong chai nang-sue doen-thaang khrab" },
  { c: "한국생활", ko: "예약이 필요합니다.", th: "ต้องจองก่อนครับ", ro: "dtong jong gon khrab" },
  { c: "한국생활", ko: "쓰레기는 정해진 날에 버립니다.", th: "ต้องทิ้งขยะตามวันที่กำหนดครับ", ro: "dtong thing kha-ya taam wan thee gam-not khrab" },
  { c: "한국생활", ko: "인터넷이 필요합니다.", th: "ต้องใช้อินเทอร์เน็ตครับ", ro: "dtong chai internet khrab" },
  { c: "한국생활", ko: "제가 확인해 보겠습니다.", th: "ผมจะตรวจสอบให้ครับ", ro: "phom ja dtruat-sop hai khrab" }
];

window.THAI_LETTERS = [
  { type: "자음", char: "ก", name: "กอ ไก่", sound: "gaw gai · 한국어 ㄱ에 가까운 소리", example: "ไก่(gai) 닭" },
  { type: "자음", char: "ข", name: "ขอ ไข่", sound: "khor khai · 숨이 섞인 ㅋ 계열", example: "ไข่(khai) 달걀" },
  { type: "자음", char: "ค", name: "คอ ควาย", sound: "khor khwaai · ㅋ 계열", example: "ควาย(khwaai) 물소" },
  { type: "자음", char: "ง", name: "งอ งู", sound: "ngor nguu · 받침 ㅇ/ng 소리", example: "งู(nguu) 뱀" },
  { type: "자음", char: "จ", name: "จอ จาน", sound: "jor jaan · ㅈ에 가까운 소리", example: "จาน(jaan) 접시" },
  { type: "자음", char: "ช", name: "ชอ ช้าง", sound: "chor chaang · ㅊ 계열", example: "ช้าง(chaang) 코끼리" },
  { type: "자음", char: "ซ", name: "ซอ โซ่", sound: "sor soh · ㅅ/s 소리", example: "โซ่(soh) 사슬" },
  { type: "자음", char: "ด", name: "ดอ เด็ก", sound: "dor dek · ㄷ에 가까운 소리", example: "เด็ก(dek) 아이" },
  { type: "자음", char: "ต", name: "ตอ เต่า", sound: "dtor dtao · 된 ㄸ/ㄷ 계열", example: "เต่า(dtao) 거북이" },
  { type: "자음", char: "ท", name: "ทอ ทหาร", sound: "thor tha-haan · ㅌ 계열", example: "ทหาร(tha-haan) 군인" },
  { type: "자음", char: "น", name: "นอ หนู", sound: "nor nuu · ㄴ 소리", example: "หนู(nuu) 쥐" },
  { type: "자음", char: "บ", name: "บอ ใบไม้", sound: "bor bai-mai · ㅂ에 가까운 소리", example: "ใบไม้(bai-mai) 잎" },
  { type: "자음", char: "ป", name: "ปอ ปลา", sound: "bpor bplaa · 된 ㅃ/ㅂ 계열", example: "ปลา(bplaa) 물고기" },
  { type: "자음", char: "ผ", name: "ผอ ผึ้ง", sound: "phor pheung · ㅍ 계열", example: "ผึ้ง(pheung) 벌" },
  { type: "자음", char: "พ", name: "พอ พาน", sound: "phor phaan · ㅍ 계열", example: "พาน(phaan) 쟁반" },
  { type: "자음", char: "ฟ", name: "ฟอ ฟัน", sound: "for fan · f 소리", example: "ฟัน(fan) 이빨" },
  { type: "자음", char: "ม", name: "มอ ม้า", sound: "mor maa · ㅁ 소리", example: "ม้า(maa) 말" },
  { type: "자음", char: "ย", name: "ยอ ยักษ์", sound: "yor yak · y/이 계열", example: "ยักษ์(yak) 거인" },
  { type: "자음", char: "ร", name: "รอ เรือ", sound: "ror ruea · r 소리", example: "เรือ(ruea) 배" },
  { type: "자음", char: "ล", name: "ลอ ลิง", sound: "lor ling · ㄹ/l 소리", example: "ลิง(ling) 원숭이" },
  { type: "자음", char: "ว", name: "วอ แหวน", sound: "wor waen · w 소리", example: "แหวน(waen) 반지" },
  { type: "자음", char: "ส", name: "สอ เสือ", sound: "sor suea · ㅅ/s 소리", example: "เสือ(suea) 호랑이" },
  { type: "자음", char: "ห", name: "หอ หีบ", sound: "hor heep · h 소리", example: "หีบ(heep) 상자" },
  { type: "자음", char: "อ", name: "ออ อ่าง", sound: "or aang · 모음 받침/무음 자음 역할", example: "อ่าง(aang) 대야" },

  { type: "모음", char: "ะ", name: "สระ อะ", sound: "a · 짧은 아", example: "จะ(ja) ~할 것이다" },
  { type: "모음", char: "า", name: "สระ อา", sound: "aa · 긴 아", example: "มา(maa) 오다" },
  { type: "모음", char: "ิ", name: "สระ อิ", sound: "i · 짧은 이", example: "กิน(gin) 먹다" },
  { type: "모음", char: "ี", name: "สระ อี", sound: "ii · 긴 이", example: "ดี(dee) 좋다" },
  { type: "모음", char: "ึ", name: "สระ อึ", sound: "ue · 짧은 으 계열", example: "หนึ่ง(neung) 하나" },
  { type: "모음", char: "ื", name: "สระ อือ", sound: "ueu · 긴 으 계열", example: "ชื่อ(chue) 이름" },
  { type: "모음", char: "ุ", name: "สระ อุ", sound: "u · 짧은 우", example: "คุณ(khun) 당신" },
  { type: "모음", char: "ู", name: "สระ อู", sound: "uu · 긴 우", example: "ดู(duu) 보다" },
  { type: "모음", char: "เ", name: "สระ เอ", sound: "ee/eh · 에 계열", example: "เกาหลี(gao-lee) 한국" },
  { type: "모음", char: "แ", name: "สระ แอ", sound: "ae · 애 계열", example: "แม่(mae) 엄마" },
  { type: "모음", char: "โ", name: "สระ โอ", sound: "oh · 오 계열", example: "โต๊ะ(dto) 책상" },
  { type: "모음", char: "ใ", name: "สระ ใอ", sound: "ai · 아이", example: "ใช่(chai) 맞다" },
  { type: "모음", char: "ไ", name: "สระ ไอ", sound: "ai · 아이", example: "ไทย(thai) 태국" },
  { type: "모음", char: "ำ", name: "สระ อำ", sound: "am · 암", example: "น้ำ(naam) 물" }
];

window.KOREAN_LETTERS = [
  { type: "พยัญชนะเกาหลี", char: "ㄱ", name: "기역", sound: "g/k · เสียงใกล้ ก/ค", example: "가(ga)" },
  { type: "พยัญชนะเกาหลี", char: "ㄴ", name: "니은", sound: "n · เสียงใกล้ น", example: "나(na)" },
  { type: "พยัญชนะเกาหลี", char: "ㄷ", name: "디귿", sound: "d/t · เสียงใกล้ ด/ท", example: "다(da)" },
  { type: "พยัญชนะเกาหลี", char: "ㄹ", name: "리을", sound: "r/l · เสียงอยู่ระหว่าง ร และ ล", example: "라(ra)" },
  { type: "พยัญชนะเกาหลี", char: "ㅁ", name: "미음", sound: "m · เสียงใกล้ ม", example: "마(ma)" },
  { type: "พยัญชนะเกาหลี", char: "ㅂ", name: "비읍", sound: "b/p · เสียงใกล้ บ/ป", example: "바(ba)" },
  { type: "พยัญชนะเกาหลี", char: "ㅅ", name: "시옷", sound: "s · เสียงใกล้ ซ/ส", example: "사(sa)" },
  { type: "พยัญชนะเกาหลี", char: "ㅇ", name: "이응", sound: "ng หรือไม่มีเสียงเมื่อต้นพยางค์", example: "아(a), 강(gang)" },
  { type: "พยัญชนะเกาหลี", char: "ㅈ", name: "지읒", sound: "j · เสียงใกล้ จ", example: "자(ja)" },
  { type: "พยัญชนะเกาหลี", char: "ㅊ", name: "치읓", sound: "ch · เสียงใกล้ ช", example: "차(cha)" },
  { type: "พยัญชนะเกาหลี", char: "ㅋ", name: "키읔", sound: "k · เสียงใกล้ ค/ข", example: "카(ka)" },
  { type: "พยัญชนะเกาหลี", char: "ㅌ", name: "티읕", sound: "t · เสียงใกล้ ท", example: "타(ta)" },
  { type: "พยัญชนะเกาหลี", char: "ㅍ", name: "피읖", sound: "p · เสียงใกล้ พ/ผ", example: "파(pa)" },
  { type: "พยัญชนะเกาหลี", char: "ㅎ", name: "히읗", sound: "h · เสียงใกล้ ห", example: "하(ha)" },
  { type: "สระเกาหลี", char: "ㅏ", name: "아", sound: "a · เสียง อา", example: "아(a)" },
  { type: "สระเกาหลี", char: "ㅑ", name: "야", sound: "ya · เสียง ยา", example: "야(ya)" },
  { type: "สระเกาหลี", char: "ㅓ", name: "어", sound: "eo · เสียง ออ/เออ", example: "어(eo)" },
  { type: "สระเกาหลี", char: "ㅕ", name: "여", sound: "yeo · เสียง ยอ/เยอ", example: "여(yeo)" },
  { type: "สระเกาหลี", char: "ㅗ", name: "오", sound: "o · เสียง โอ", example: "오(o)" },
  { type: "สระเกาหลี", char: "ㅛ", name: "요", sound: "yo · เสียง โย", example: "요(yo)" },
  { type: "สระเกาหลี", char: "ㅜ", name: "우", sound: "u · เสียง อู", example: "우(u)" },
  { type: "สระเกาหลี", char: "ㅠ", name: "유", sound: "yu · เสียง ยู", example: "유(yu)" },
  { type: "สระเกาหลี", char: "ㅡ", name: "으", sound: "eu · เสียง อือ", example: "으(eu)" },
  { type: "สระเกาหลี", char: "ㅣ", name: "이", sound: "i · เสียง อี", example: "이(i)" }
];
